### ISSUE TITLE
Don't make playfield tilt overshoot

### ISSUE THREAD

**Issue by Dan9er** [Drewol/unnamed-sdvx-clone#1]
When a laser slam (right angle laser), the playfield reacts by tilting. However, the tilt has an overshoot which is most noticeable [here](https://youtu.be/dfEbmBzdvYA?t=41s). **Please** remove this. This does not reflect behavior in either KShootMaina or SDVX.

**Comment by Drewol** [comment]
That video is of a very old version, the tilting does not look anything like that anymore. However, if you feel like there's anything wrong with the tilting in the latest build you can put this here or I'll just mark this as solved
