### ISSUE TITLE
Laser segments don't connect properly

### ISSUE THREAD

**Issue by Dan9er** [Drewol/unnamed-sdvx-clone#10]
OS: Windows 10 Pro 64-bit, Version 1703, Build 15063.674
Commit: [d777a48](https://github.com/Drewol/unnamed-sdvx-clone/commit/d777a4858efe79b9bfa5a5ea97b314770646b381)

[![YouTube Video](https://img.youtube.com/vi/kjkLKzJAuCM/0.jpg)](https://www.youtube.com/watch?v=kjkLKzJAuCM)

**Comment by Drewol** [comment]
There are two laser graphical errors I'm aware of, one is where the segments don't connect properly which i think is a floating point rounding error somewhere and the other is that the lasers don't re-shape properly on BPM changes.

**Comment by Dan9er** [comment]
Added video

**Comment by Drewol** [comment]
Oh, that's more intense than I've ever seen it, could you send me that chart file and I can investigate it further

**Comment by Dan9er** [comment]
@Drewol Ok, sent to you in the #development channel of the Discord

**Comment by Dan9er** [comment]
Confirmed fixed on Windows 10.
