### ISSUE TITLE
Convert code from C to C++

### ISSUE THREAD

**Issue by Dan9er** [Drewol/unnamed-sdvx-clone#12]
C is pretty much an outdated language.

**Comment by Drewol** [comment]
is this a meme?

**Comment by Dan9er** [comment]
No, I'm dead serious. Why are you using 90% C?

**Comment by Drewol** [comment]
the game itself is almost entirely cpp, it's all the third party stuff that's in c

**Comment by Dan9er** [comment]
Oh, like OpenGL? Oh ok, guess this is a wontfix then.
