### ISSUE TITLE
Game crashes with WASAPI Exclusive enabled

### ISSUE THREAD

**Issue by YChvanov** [Drewol/unnamed-sdvx-clone#129]
[old version - log_Main_Release.exe.txt](https://github.com/Drewol/unnamed-sdvx-clone/files/2568682/log_Main_Release.exe.txt)
[new version - log_usc-game.exe.txt](https://github.com/Drewol/unnamed-sdvx-clone/files/2568683/log_usc-game.exe.txt)
Temporary fix:
  Go to Main.cfg and change "WASAPI_Exclusive = True" at the bottom to "WASAPI_Exclusive = False"

**Comment by Drewol** [comment]
Did you make sure that this setting is enabled? https://cdn.discordapp.com/attachments/82229158029037568/509693883760771088/unknown.png
