### ISSUE TITLE
[Bug] Restarting during failure causes lower game speed

### ISSUE THREAD

**Issue by narcow** [Drewol/unnamed-sdvx-clone#144]
OS: Linux (x64)

Pressing F5 to restart a song as you fail out causes the game to play both audio and chart elements at a slower speed. The actual speed of this slowed playback is variable and appears to depend on when during the failure the restart command is issued. I suspect that the slowdown applied during the display of the failure message is carrying over into the new play.

I have not tested whether or not this also occurs when restarting during the track clear message.

**Comment by Hinara** [comment]
Is it fixed ? Wasn't able to reproduce

**Comment by narcow** [comment]
I am no longer able to reproduce this issue; it seems to be fixed.
