### ISSUE TITLE
Unable to build on Linux

### ISSUE THREAD

**Issue by NovaPhoenix** [Drewol/unnamed-sdvx-clone#145]
After cloning and initializing the submodules, when doing `cmake .` I get this:
```
~/b/unnamed-sdvx-clone ❯❯❯ cmake .
CMake Error at third_party/CMakeLists.txt:14 (add_subdirectory):
  add_subdirectory given source "cpr" which is not an existing directory.


CMake Error at third_party/CMakeLists.txt:15 (target_include_directories):
  Cannot specify include directories for target "cpr" which is not built by
  this project.


-- Configuring incomplete, errors occurred!
See also "/home/phoenix/builds/unnamed-sdvx-clone/CMakeFiles/CMakeOutput.log".
```
Manually adding CPR as a submodule does not fix this.

**Comment by narcow** [comment]
Issue confirmed when I build the latest release. Commit `f74774abe58cc6c9a81eae19b8b91a10487f5fec` (08th December) from before cpr was added to the project builds successfully.

**Comment by Drewol** [comment]
I think linux building should be fixed now (i manged to build on the latest commit 9015d6a19ac38c0dafb6e89059badc15d87f6669) you have to call `git submodule update --init --recursive` and then run `cmake .` and if it still doesnt work you can try clearing your cmake cache

**Comment by NovaPhoenix** [comment]
Everything builds and runs correctly!
