### ISSUE TITLE
Building issue for Embedded on Raspberry Pi 3

### ISSUE THREAD

**Issue by supercasul** [Drewol/unnamed-sdvx-clone#150]
After I ran make on a RPi3 A+ I get an error with Tests.Game/Main.cpp, the output is as followed:

unnamed-sdvx-clone/Tests.Game/Main.cpp:9:48: error: must #include <typeinfo> before using typeid
  Logf("Available Tests:", Logger::Info, typeid(testManager).name());
                                                ^~~~~~~~~~~
Tests.Game/CMakeFiles/Tests.Game.dir/build.make:75: recipe for target 'Tests.Game/CMakeFiles/Tests.Game.dir/Main.cpp.o' failed
make[2]: *** [Tests.Game/CMakeFiles/Tests.Game.dir/Main.cpp.o] Error 1
CMakeFiles/Makefile2:559: recipe for target 'Tests.Game/CMakeFiles/Tests.Game.dir/all' failed
make[1]: *** [Tests.Game/CMakeFiles/Tests.Game.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I'm still relatively new to this so it could be something I'm doing wrong.

**Comment by Drewol** [comment]
Which version of GCC are you using?

**Comment by supercasul** [comment]
Thanks for the quick response, I'm on gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1+deb9u1).

**Comment by Drewol** [comment]
Ok, you need to be on 7 or newer I'm pretty sure, though you might have to build that from source.

**Comment by supercasul** [comment]
So after double checking it looks like it still outputs a working executable even with the error. While it's still concerning, I guess it still works in the current state.
