### ISSUE TITLE
[Suggestion for Embedded Branch] Controller Menu navigation

### ISSUE THREAD

**Issue by supercasul** [Drewol/unnamed-sdvx-clone#153]
I've currently put together a mini cabinet with an RPi3 revolving around the Embedded build and the one thing that does make it a bit inconvenient is that you cannot navigate the main menu with the controller, which would allow me to solve issues such as offset, sound, and skin changing on the go. As it currently stands, if I want to adjust any of that, I have to open up the cab and plug in a M+K and then launch it without -notitle and navigate to the menu.

While it may not be updated and is an extremely niche build, it would be nice to see this functionality. 

Picture of the cabinet
https://i.imgur.com/yW7ozM9.png

**Comment by ok2094** [comment]
I agree with the suggestion and damn that cabinet looks nice. Where did you get the sdvx skin?

**Comment by LavenderTheGreat** [comment]
Probably here: https://github.com/nieknooijens/unnamed-sdvx-clone-sdvxIV-skin

**Comment by Drewol** [comment]
A bit late but I made a new embedded version based on the current version (968decd10281e8ae221bc79bcc60ad5b138ed2e2) and that has controller navigation for the main menu. https://github.com/Drewol/unnamed-sdvx-clone/tree/embedded-new This embedded version should also be compatible with the master branch so in the near future embedded should be a part of the master branch hopefully.

**Comment by Drewol** [comment]
The new embedded version was merged into master with fc3464c4d95f9ea47abb4b5033913789081dd9f3 so it's not up to the skins to make implementations but the default should work fine and it has controller navigation of the main menu.
