### ISSUE TITLE
Double input during fast presses

### ISSUE THREAD

**Issue by Catwell123** [Drewol/unnamed-sdvx-clone#180]
For some weird reason, I'm getting what appears to be double inputs during sections of 16th notes or faster. It doesn't happen all the time, but it's consistent enough to be quite annoying as I will drop a lot of notes due to error chain. I was able to tell by doing a test chart.

Chart consisted of 4 BT pressed every 16th beat and I would eventually miss all despite the timing being fine. Then I tried it with 4 BT every 8th beat and I would notice that the white highlight for a press would be highlighted again on certain buttons each time indicating a quick press again. This does not happen on KSM.

I am using a TC+.

**Comment by Drewol** [comment]
try increasing your button bounce guard setting

**Comment by Catwell123** [comment]
that did the trick, thanks
