### ISSUE TITLE
Game doesn't start because of missing libeay32.dll binary

### ISSUE THREAD

**Issue by YChvanov** [Drewol/unnamed-sdvx-clone#186]
libeay32.dll is a part of openssl
![Clipboarder 2019 05 24](https://user-images.githubusercontent.com/25438100/58306102-0ecf9e80-7e03-11e9-9995-e59a32bc9748.png)

**Comment by Drewol** [comment]
This should be fixed now

**Comment by YChvanov** [comment]
uhm yes
