### ISSUE TITLE
Game will not build.

### ISSUE THREAD

**Issue by SnappyGithub** [Drewol/unnamed-sdvx-clone#192]
I know this issue has also happened to someone, but I have a different problem than the other guy.  
When I run the first command, which is `cmake .`, I get an error while building.
The output I receive is:  

`CMake Error at third_party/CMakeLists.txt:18 (add_subdirectory):
  The source directory
    /home/buzduc/Scrivania/unnamed-sdvx-clone-master/third_party/cpr
  does not contain a CMakeLists.txt file.
CMake Error at third_party/CMakeLists.txt:19 (target_include_directories):
  Cannot specify include directories for target "cpr" which is not built by
  this project.
CMake Error at third_party/CMakeLists.txt:23 (add_subdirectory):
  The source directory
    /home/buzduc/Scrivania/unnamed-sdvx-clone-master/third_party/discord-rpc
  does not contain a CMakeLists.txt file.
CMake Error at third_party/CMakeLists.txt:24 (target_include_directories):
  Cannot specify include directories for target "discord-rpc" which is not
  built by this project.
CMake Error at /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find SDL2 (missing: SDL2_INCLUDE_DIR SDL2_LIBRARY)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  third_party/FindSDL2.cmake:13 (find_package_handle_standard_args)
  third_party/FindLibraries.cmake:4 (find_package)
  third_party/CMakeLists.txt:45 (include)
-- Configuring incomplete, errors occurred!
See also "/home/buzduc/Scrivania/unnamed-sdvx-clone-master/CMakeFiles/CMakeOutput.log".`.  

After that, it created a file named CMakeCache.txt which I guess needs a slight change so, if anyone wants to do it, here it is. [CMakeCache.txt](https://github.com/Drewol/unnamed-sdvx-clone/files/3272628/CMakeCache.txt)

Did I forgot to install the libraries or is it another problem?  

I run Ubuntu 16.04 LTS and I use CMake 3.15.0-rc1.

**Comment by Drewol** [comment]
did you run `git submodule update --init --recursive` ?

**Comment by SnappyGithub** [comment]
no. why?

**Comment by SnappyGithub** [comment]
no. why?

**Comment by SnappyGithub** [comment]
also i didnt download the files using git.

**Comment by Drewol** [comment]
Use git clone to download the project and then also run `git submodule update --init --recursive` to download the required third party project files.

**Comment by SnappyGithub** [comment]
can you write me the command?

**Comment by Drewol** [comment]
`git clone https://github.com/Drewol/unnamed-sdvx-clone.git`

**Comment by SnappyGithub** [comment]
i recieved an an error using `git submodule update --init --recursive`:
`fatal: Not a git repository (or any of the parent directories): .git`

**Comment by SnappyGithub** [comment]
what do i do?

**Comment by SnappyGithub** [comment]
?????

**Comment by Drewol** [comment]
You have to have the be in the root folder of the game when you run the `git submodule update --init --recursive` command so after you cloned you have to do `cd unnamed-sdvx-clone`

**Comment by SnappyGithub** [comment]
ok.

**Comment by SnappyGithub** [comment]
done.
what do i do now?

**Comment by SnappyGithub** [comment]
?

**Comment by Drewol** [comment]
Check the build instructions in the readme https://github.com/Drewol/unnamed-sdvx-clone#linux which should be enough. 

And please do not use this as a chat as me and others who are watching the project get an email for every comment you make. Try more things out before making comments and write more information about what went wrong when you do make a comment.

**Comment by SnappyGithub** [comment]
oh. btw thank you.

**Comment by SnappyGithub** [comment]
Hey, @Drewol.  
It's me, @SnappyGithub, the author.  
I understood that your and the other guys that are watching get bloated up their inboxes with my useless comments (I'm only 10 and i don't really program that much.) so, i'm gonna explain my new problem into one comment.  

After doing all the commands you said, I ran `cmake .` and then encountered a new problem in the building of the program and the output i received was:  

`-- Checking compiler flags for C++11 support.  
-- C++11 is supported.  
-- C++ Requests CMake Options  
-- =======================================================  
--   USE_SYSTEM_CURL: OFF  
--   BUILD_CPR_TESTS: OFF  
--   GENERATE_COVERAGE: OFF  
--   CPR_CURL_NOSIGNAL: OFF  
--   USE_SYSTEM_GTEST: OFF  
--   CMAKE_USE_OPENSSL: ON  
-- =======================================================
-- Not using system Curl, using built-in curl project instead.  
CMake Warning at third_party/cpr/opt/curl/CMakeLists.txt:50 (message):
the curl cmake build system is poorly maintained.  Be aware
-- curl version=[7.56.0-DEV]
-- Performing Test OPT-Wstrict-aliasing=3
-- Performing Test OPT-Wstrict-aliasing=3 - Success
Found *nroff option: -- -man
CMake Error at /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.15/Modules/FindOpenSSL.cmake:413 (find_package_handle_standard_args)
  third_party/cpr/opt/curl/CMakeLists.txt:357 (find_package)
-- Configuring incomplete, errors occurred!
See also "/home/buzduc/Scrivania/unnamed-sdvx-clone/CMakeFiles/CMakeOutput.log".
See also "/home/buzduc/Scrivania/unnamed-sdvx-clone/CMakeFiles/CMakeError.log".`.

Can you write me down in a comment what to do please?  
(To thank you I won't write it in a comment, i will just add you a thumbs up emoji.)
