### ISSUE TITLE
can't link libarchive on mac 

### ISSUE THREAD

**Issue by jgoulet921** [Drewol/unnamed-sdvx-clone#196]
i get this error while trying to link libarchive

 Refusing to link macOS-provided software: libarchive
If you need to have libarchive first in your PATH run:
  echo 'export PATH="/usr/local/opt/libarchive/bin:$PATH"' >> ~/.bash_profile

For compilers to find libarchive you may need to set:
  export LDFLAGS="-L/usr/local/opt/libarchive/lib"
  export CPPFLAGS="-I/usr/local/opt/libarchive/include"

**Comment by Drewol** [comment]
Hi, I've updated the build instructions for mac, could you verify that the game builds now?

**Comment by Drewol** [comment]
should be resolved/no response in too long, reopen if issue persists
