### ISSUE TITLE
CMake unable to find JPEG when trying to build

### ISSUE THREAD

**Issue by SugoiSheep** [Drewol/unnamed-sdvx-clone#197]
I don't wanna be THAT guy again, but I couldn't find any solution on google.
when I run cmake . it spews out an error stating it can't find JPEG.
I am running Ubuntu 19.04

```
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.13/Modules/FindJPEG.cmake:89 (find_package_handle_standard_args)
  third_party/FindLibraries.cmake:6 (find_package)
  third_party/CMakeLists.txt:46 (include)
```

**Comment by Drewol** [comment]
Did you install libjpeg (and all the other packages listed in build.linux)?

**Comment by SugoiSheep** [comment]
I have downloaded the .tar package via the link provided, however I might have installed it wrong.
I have put the resulting folder you get by unpacking in the home directory. Is this right?

**Comment by Drewol** [comment]
Most of them should be available through your systems package manager but if they aren't there or if the ones that aren't there work then you can do the following.

It should come with install instructions but for a lot of libraries on linux it's:
1. extract the archive
2. cd to the extracted directory
3. `./configure`
4. `make`
5. `make install`

**Comment by SugoiSheep** [comment]
ah, I have installed libjpeg via the the package mangager. my problem was that I tried sudo apt libjpeg, while I shoud have done libjpeg-dev.
it might be an idea to put these package names in the build.linux to further streamline the proces of bulding.
