### ISSUE TITLE
[Feature] Adding animations to a chart using Lua

### ISSUE THREAD

**Issue by skielred** [Drewol/unnamed-sdvx-clone#200]
It is currently possible to load a fragment shader as the background of a chart and do some shading logic to make stuff appear. However this is overcomplicated and does not cover some interesting cases.

It should be possible to load a script from a chart that enables:
- Accessing and animating current UI elements
  Example scenario: hiding some elements during the climax parts like in KAC finals
- Displaying text and images and animating them in the foreground
  Example scenario: tutorials and two-torial
- Displaying text and images and animating them in the background
  Example scenario: most KAC and boss songs, Firestorm
- Playing sounds
  Example scenario: SFX during a tutorial, if the tutorial has different difficulties, each difficulty would get its own SFX so it's easier to script it rather than making different music files with the SFX pre-applied.

Animations like in "I" could be covered by animating an image in the foreground or by using shaders, not sure which is most appropriated.

This would be the features to get as much control on the chart as what we can see on official SDVX, but getting as much as possible of the game exposed through scripting for chart creators would open to many other possibilities too.

My initial concern has been because I wanted to display a character in the background similar to what we see in Firestorm, this is possible by loading a fragment shader as the background and animating it but Lua scripting would be more convenient, should expose more features and would be way more fitting.

**Comment by Drewol** [comment]
Most of this should now be possible after the bg rework. https://unnamed-sdvx-clone.readthedocs.io/en/latest/bgfg.html You can reopen the issue if you feel that this is not enough.
