### ISSUE TITLE
Won't Build on Mac (Linker Issue)

### ISSUE THREAD

**Issue by pandazzo** [Drewol/unnamed-sdvx-clone#201]
Having trouble building this on a mac. Received the following error at 90% built:

> Falling back to library file for linking.
> Undefined symbols for architecture x86_64:
>   "_archive_read_free", referenced from:
>       DownloadScreen::m_ArchiveLoop() in DownloadScreen.cpp.o
>   "_archive_read_support_filter_all", referenced from:
>       DownloadScreen::m_ArchiveLoop() in DownloadScreen.cpp.o
>       DownloadScreen::m_ProcessArchiveResponses() in DownloadScreen.cpp.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [bin/usc-game] Error 1
> make[1]: *** [Main/CMakeFiles/usc-game.dir/all] Error 2
> make: *** [all] Error 2

**Comment by KagamineRinSuki** [comment]
I met the same problem

**Comment by Drewol** [comment]
I do not have a mac so I cannot work out this issue but it definitely seems to be caused by libarchive in some way so it might be good to try to find another way of adding it to the project besides brew.

**Comment by KagamineRinSuki** [comment]
I have solved this problem:
https://github.com/visualboyadvance/visualboyadvance/issues/7
It was because cmake can not use the brew version automatically, we should set it manually.
But I met another bug when I was trying to  change the keyboard settings:
> [08:55:25][Warning] Failed to open file for reading /Users/me/fonts: 2

Why did it read the fonts file from my root directory?
So I have to move the file to my root.

**Comment by Drewol** [comment]
From where were you running the game? I thought I had fixed the issue of it looking in the wrong places if it was ran in a place other than the game bin directory in 4c5b0bda86b932f948b6fa21c161960cb6319f53 but maybe not, but that's a separate issue anyway.

**Comment by KagamineRinSuki** [comment]
I just run it in the generated bin directory.

**Comment by Drewol** [comment]
Something probably goes wrong [here](https://github.com/Drewol/unnamed-sdvx-clone/blob/master/Shared/src/Unix/Path.cpp#L86) then.

**Comment by Drewol** [comment]
I have now managed to build and run the game on MacOS without any major issues

**Comment by Drewol** [comment]
Seems resolved, reopen if not

**Comment by A0MASA** [comment]
similar problem except with this error 

> $ make
[  1%] Built target sqlite3
[  2%] Built target GLEW
[  3%] Built target minimp3
[ 10%] Built target soundtouch
[ 11%] Built target nanovg
[ 27%] Built target lua
[ 33%] Built target cpr
[ 36%] Built target discord-rpc
[ 50%] Built target Shared
[ 58%] Built target Graphics
[ 59%] Built target GUI
[ 65%] Built target Audio
[ 70%] Built target Beatmap
[ 71%] Linking CXX executable ../bin/usc-game
Undefined symbols for architecture x86_64:
  "GameConfig::VERSION", referenced from:
      Application::m_LoadConfig() in Application.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/usc-game] Error 1
make[1]: *** [Main/CMakeFiles/usc-game.dir/all] Error 2
make: *** [all] Error 2

> 
I thought it was a problem with my OS but updating didn't help
