### ISSUE TITLE
Adjust timing windows to be more akin to Sound Voltex

### ISSUE THREAD

**Issue by LavenderTheGreat** [Drewol/unnamed-sdvx-clone#204]
Notably on harder charts it's almost impossible for me to begin to get better because missing notes or hitting empty lanes seems to ERROR/miss any note within the next second on that lane. While I believe this is intended behavior I believe the timing window for an ERROR hit to occur is at least 3x too large. I have also heard in general that the timing window of USC is really tight, so that might want to be adjusted too. A solution could be the timing window settings you see in stuff like TJAPlayer 3 for Taiko, or the Judge settings in stepmania.

**Comment by Drewol** [comment]
Closing as a judge option has been added in 3c7c17053c1a354fbabfd7bc21e0f6cd07a17971
