### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by 3laww** [Drewol/unnamed-sdvx-clone#222]
I have two computers and both are Windows 10, 64-bit versions. However, the latest Windows build works on one computer but not on another. I wonder why it doesn't work on this computer. Is there any programs I need to install to run the USC file?

**Comment by Hinara** [comment]
Hello,

A little thing, when you have a problem like that try to correctly name your issue
Concerning your problem, can you run usc from command line ? Like powershell or cmd ? And provide us your log ?

**Comment by Drewol** [comment]
No response in too long/not enough information given
