### ISSUE TITLE
Help building macOS version

### ISSUE THREAD

**Issue by Rorori** [Drewol/unnamed-sdvx-clone#227]
I'm having trouble building the game for macOS:

I installed the dependencies listed, but mac is giving me a warning saying I cannot link libarchive:

Warning: Refusing to link macOS-provided software: libarchive
If you need to have libarchive first in your PATH run:
  echo 'export PATH="/usr/local/opt/libarchive/bin:$PATH"' >> ~/.bash_profile

Subsequently, using the command "cmake ." results in the following errors:

CMake Error at third_party/CMakeLists.txt:22 (add_subdirectory):
  The source directory

    /Users/Dychonics/downloads/unnamed-sdvx-clone/third_party/cpr

  does not contain a CMakeLists.txt file.

CMake Error at third_party/CMakeLists.txt:23 (target_include_directories):
  Cannot specify include directories for target "cpr" which is not built by
  this project.

CMake Error at third_party/CMakeLists.txt:27 (add_subdirectory):
  The source directory

    /Users/Dychonics/downloads/unnamed-sdvx-clone/third_party/discord-rpc

  does not contain a CMakeLists.txt file.

CMake Error at third_party/CMakeLists.txt:28 (target_include_directories):
  Cannot specify include directories for target "discord-rpc" which is not
  built by this project.

CMake Error at /usr/local/Cellar/cmake/3.15.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibArchive (missing: LibArchive_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.15.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.15.3/share/cmake/Modules/FindLibArchive.cmake:52 (find_package_handle_standard_args)
  third_party/FindLibraries.cmake:9 (find_package)
  third_party/CMakeLists.txt:46 (include)

-- Configuring incomplete, errors occurred!

I am not sure what to do from here...

**Comment by Drewol** [comment]
for the cpr and discord error it seems you need to run `git submodule update --init --recursive`
for the libarchive error see #201

**Comment by Rorori** [comment]
I now run into an error while making:

/Users/Dychonics/downloads/unnamed-sdvx-clone/Main/SongSelect.cpp:1138:39: error: non-constant-expression cannot be narrowed from type 'MapTime' (aka 'int') to 'uint32' (aka 'unsigned int') in initializer
      list [-Wc++11-narrowing]
                PreviewParams params = { audioPath, diff->settings.previewOffset, diff->settings.previewDuration };
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Dychonics/downloads/unnamed-sdvx-clone/Main/SongSelect.cpp:1138:39: note: insert an explicit cast to silence this issue
                PreviewParams params = { audioPath, diff->settings.previewOffset, diff->settings.previewDuration };
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                    static_cast<uint32>(        )
/Users/Dychonics/downloads/unnamed-sdvx-clone/Main/SongSelect.cpp:1138:69: error: non-constant-expression cannot be narrowed from type 'MapTime' (aka 'int') to 'uint32' (aka 'unsigned int') in initializer
      list [-Wc++11-narrowing]
                PreviewParams params = { audioPath, diff->settings.previewOffset, diff->settings.previewDuration };
                                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Rorori** [comment]
Thank you for helping by the way!

**Comment by Rorori** [comment]
Here, I'll close this thread and open another one later, as this looks like a problem with the code itself.
