### ISSUE TITLE
Starting a song not working [Linux]

### ISSUE THREAD

**Issue by lukeoftheaura** [Drewol/unnamed-sdvx-clone#23]
selecting a song from the song list doesn't work on a linux build from the latest master. The rest of the game works fine, if I start a song from the command-line.

**Comment by Drewol** [comment]
did you bind start to anything? by default it's set to `1`

I just compiled and tested the latest master on my own linux machine and it works there.

**Comment by lukeoftheaura** [comment]
rebinding start works. I'm so stupid.
