### ISSUE TITLE
Cannot go back to title from song select using controller

### ISSUE THREAD

**Issue by NutchapolSal** [Drewol/unnamed-sdvx-clone#234]
As title says

3 BT + start cause it to go to the title screen and immediately come back to song select

Culprit: titlescreen.lua handle_controller()

Possible fix: 
```diff
@@ -122,8 +122,13 @@
 
 local lastKnobs = nil
 local knobProgress = 0
+local enableSelect = false
 function handle_controller()
-    if game.GetButton(game.BUTTON_STA) then
+    if not(enableSelect) then
+        if not(game.GetButton(game.BUTTON_STA)) then
+            enableSelect = true
+        end
+    elseif game.GetButton(game.BUTTON_STA) then
 		buttons[cursorIndex][2]()
 	end
```
`enableSelect` will first be false when going back to title screen, and will be true only when start is released

when `enableSelect` is true then start will be able to activate menu buttons

**Comment by Drewol** [comment]
This should not be an issue any more, reopen if it's still there.
