### ISSUE TITLE
Program stops when meets minus tempo

### ISSUE THREAD

**Issue by hyeonsoft** [Drewol/unnamed-sdvx-clone#240]
example:
t=-210
the chart which contains minus tempo make it stop.

**Comment by Drewol** [comment]
I am quite sure that negative BPM (`t=`) is not a thing in ksh, to make the chart stop for a while in ksh you put `stop=x`  where x is the length of the stop and 192 is 1 measure at 4/4 time signature.

**Comment by hyeonsoft** [comment]
> I am quite sure that negative BPM (`t=`) is not a thing in ksh, to make the chart stop for a while in ksh you put `stop=x` where x is the length of the stop and 192 is 1 measure at 4/4 time signature.

I supposed to make the chart go reverse. So these tricks would be not supported?

**Comment by Drewol** [comment]
Reversing a chart was a bug in ksm that happened when you put two stops on top of each other, it was patched our of ksm but I intentionally made it work like that in USC

**Comment by hyeonsoft** [comment]
Thank you for your comment.
