### ISSUE TITLE
B.B.K.K.B.K.K. WORLD'S END doesn't work in USC

### ISSUE THREAD

**Issue by Klodaa12** [Drewol/unnamed-sdvx-clone#259]
BPM changes in this map doesn't affect it at all, I mean the parts where lasers should go backwards. Does it even work or maybe does somebody have a link to working version of this map?

**Comment by Drewol** [comment]
Do you use the cmod hispeed setting?

**Comment by Klodaa12** [comment]
I was using mainly this mod, but I tried other two on this map and still doesn't work

**Comment by NutchapolSal** [comment]
iirc if you played it on latest ksh, it will automatically remove double pauses(reverse) from the .ksh file. and it does work on USC (unless updates broke that)

you will have to get a new copy of the map

**Comment by Klodaa12** [comment]
and where do I find it? I cannot find now

**Comment by NutchapolSal** [comment]
https://www.youtube.com/watch?v=jyDJhEfIMWY

**Comment by Klodaa12** [comment]
thank you so much!

**Comment by Klodaa12** [comment]
but wait. this map doesn't have music and it doesn't show in the song select screen

**Comment by Klodaa12** [comment]
I added music by myself but now when I try to play this, the game crashes

**Comment by Hinara** [comment]
Was caused because the path contains non ansi characters

**Comment by hyeonsoft** [comment]
You should change the music file bame in your text editor.
Actually, that chart has also a problem that it doesnot move for some first laser notes

**Comment by hyeonsoft** [comment]
*I tested it in last release, not last dev build

**Comment by Klodaa12** [comment]
I don't quite understand. What exactly am I supposed to do?

**Comment by Hinara** [comment]
Try again to launch the map with the new release
(Don't download it from release part of github but from release link on the main page: https://drewol.me/Downloads/Game.zip )
If it still crashing reopen the issue
