### ISSUE TITLE
my game won't fullscreen and the knob speed is really high

### ISSUE THREAD

**Issue by NotZora** [Drewol/unnamed-sdvx-clone#276]
the title says it all but i got the latest windows build version

**Comment by Drewol** [comment]
`Alt+Enter` is the hotkey for fullscreening and the knob speed can be adjusted in settings.

**Comment by NotZora** [comment]
also the settings dont save

**Comment by NotZora** [comment]
> `Alt+Enter` is the hotkey for fullscreening and the knob speed can be adjusted in setting

also the settings dont save

**Comment by Drewol** [comment]
Do you have write permissions to the location you're starting the game from? / Do settings save when you run the game as admin?

**Comment by NotZora** [comment]
little brain i didn't run in administrator ty so much (lazer sense still high but might be the controller)

**Comment by Hinara** [comment]
@NotZora if this is fixed can you close this issue ?
