### ISSUE TITLE
[Bug] Laser sensitivity calibration gives completely inconsistent results.

### ISSUE THREAD

**Issue by Dahamugo** [Drewol/unnamed-sdvx-clone#277]
Every time I follow the procedure in settings > input > calibrate laser sensitivity, I get a different result, which seems to depend on what the current laser sensitivity value is.

For example:
1. Manually set sensitivity to 2 (or as close as I can get), and follow the procedure. Resulting sensitivity is 0.06
2. Repeat the procedure with the sensitivity set to 0.06. Resulting sensitivity is 0.0012
3. Manually set sensitivity to 2, follow procedure again. Resulting sensitivity is 0.039
4. Set sensitivity to 0, follow procedure again. Resulting sensitivity is 0.0

As it stands, I have absolutely no clue what the correct sensitivity value should be for my current setup.

**Comment by ttepatti** [comment]
I'm also getting this issue using the latest build on Ubuntu 19.10. I'm playing with an SVSE5 controller and every time I calibrate the lasers I get a different result.
