### ISSUE TITLE
[Bug] Linux  sporadic (core dump) during song select

### ISSUE THREAD

**Issue by nabulator** [Drewol/unnamed-sdvx-clone#286]
During song selection, core dumps sporadically. Seems to happen mostly with songs in Nautica folder. 

From my STD_OUT
`[22:53:51][Error] ov_open_callbacks failed with code -128
usc-game: ./unnamed-sdvx-clone/Shared/include/Shared/Ref.hpp:272: int32* Ref<T>::m_CreateNewCounter() [with T = AudioStream; int32 = int]: Assertion `m_data' failed.
Aborted (core dumped)

**To Reproduce**
1. Download some Nautica songs
2. Scroll around in song select
3. sometimes get a crash

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 Bionic
 - GPU: Intel Integrated
 - Version: commit 2456d6c461b57555ba1246a85ad974b8584987fd (Dec 30 2019 so pretty recent) self compiled with cmake and gcc

**Additional context**
Game runs fine for 10-20 minutes. I want to say it's malformed Songs because I could only get it crash with Nautica songs. Look like some memory problem...

**Comment by Drewol** [comment]
Did you run cmake with `-DCMAKE_BUILD_TYPE=Release`? Without it there are some debug asserts that can get hit pretty often, after rebuilding with it the songs will likely still be unplayable but the game should stop crashing.

**Comment by nabulator** [comment]
Oops! Forgot to do that. This fixes this issue.
