### ISSUE TITLE
Autoplay doesn't work

### ISSUE THREAD

**Issue by Dan9er** [Drewol/unnamed-sdvx-clone#29]

**Comment by Dan9er** [comment]
I just tried activating autoplay via command line and that didn't work either!

**Comment by Drewol** [comment]
Since I removed the hardcoded enter bind the way to autoplay is Ctrl + [whatever your start is]

The autoplay command line arguments only apply when you also pass it a ksh file

**Comment by Dan9er** [comment]
But I did set Start to enter.

**Comment by Dan9er** [comment]
This was fixed in 9d028d7654cebf4e3c9145b649337cb1fe7bff00.

@Drewol *please* remember to close via commit description.

**Comment by Drewol** [comment]
that commit was before this issue and autoplay mostly worked even before that it was just holds that had some weirdness on autoplay that i fixed in that commit.
