### ISSUE TITLE
Error on Mac

### ISSUE THREAD

**Issue by Julienlemab** [Drewol/unnamed-sdvx-clone#294]
152 warnings and 1 error generated.
make[2]: *** [Main/CMakeFiles/usc-game.dir/src/Application.cpp.o] Error 1
make[1]: *** [Main/CMakeFiles/usc-game.dir/all] Error 2
make: *** [all] Error 2

**Comment by Drewol** [comment]
You need to include some things before that which shows where the error actually occurred.

**Comment by Julienlemab** [comment]
Here's the full log on a .txt file (can't find the .log)
[Error.txt](https://github.com/Drewol/unnamed-sdvx-clone/files/4204126/Error.txt)

**Comment by Drewol** [comment]
did you install libarchive with homebrew and did you run the `mac-cmake.sh` script?

**Comment by Julienlemab** [comment]
I installed libarchive 2.x because before that, in the 3.x version it wouldn't work, I ran the Mac-cmake.sh script to be simple I used those commands:
git clone https://github.com/Drewol/unnamed-sdvx-clone.git
cd unnamed-sdvx-clone
git submodule update --init --recursive
./mac-cmake.sh
make
the log is from the make command

**Comment by Drewol** [comment]
libarchive 3.x needs to be installed and if you can't install it through homebrew and you use some other way you need to make sure that the paths in the `mac-cmake.sh` script point to the location that libarchive has been installed to.

**Comment by Julienlemab** [comment]
Thanks, I'll try that

**Comment by Julienlemab** [comment]
it still shows me the same error

**Comment by Julienlemab** [comment]
never mind, thank you, nothing worked, above there, I just had to reinstall brew and lib archive, still thank you
