### ISSUE TITLE
[Feature] Discord Rich Presence

### ISSUE THREAD

**Issue by hw4n** [Drewol/unnamed-sdvx-clone#299]
Hi! This is not a direct feature for the game, but it might be cool to have this feature.
Some people would know this already, discord shows what game are you playing or specifically what stage or map are you playing.

This is an example from the game osu!:
![image](https://user-images.githubusercontent.com/38372575/75035554-11c30100-54f3-11ea-9297-87a4ef431ee0.png)

Many people(especially gamers) already know and use discord a lot, this feature might help the game promote broadly.

Since discord already has API documents about this feature, rich presence can be implemented as an extra addition to the game, whenever the game is almost finished.

This would have low priority in the development, but I'm pretty sure it will make the game much cooler.

**Comment by Drewol** [comment]
This is already in the game 
![image](https://user-images.githubusercontent.com/11597870/75036258-bc1a3480-54b1-11ea-9985-e6bf477b5c63.png)

**Comment by hw4n** [comment]
Is game invite with discord will be a thing later? I've noticed osu has that feature.

**Comment by Drewol** [comment]
That is also already in the game.
![image](https://user-images.githubusercontent.com/11597870/75043410-56817480-54c0-11ea-85fe-eb176907aa95.png)

**Comment by hw4n** [comment]
Are these features added from the latest builds?
or this was already here but I did not notice because it doesn't automatically show on discord?

**Comment by Drewol** [comment]
It was added in 2018 https://github.com/Drewol/unnamed-sdvx-clone/commit/ca134edfdc15ccb5f6484625506d3db10b685813 and it should show up in discord as long as you don't have game activity turned off in discord

**Comment by hw4n** [comment]
How did I not notice this before? I did turn show game activity on...

I'm sorry for opening an extra duplicate issue on this one.
