### ISSUE TITLE
Won't detect song folders.

### ISSUE THREAD

**Issue by nut573** [Drewol/unnamed-sdvx-clone#3]
Always get this error in log_Main_Release.exe.txt `[01:49:54][Warning] Can't run ScanFiles, "\songs"
" is not a folder` Changing the path on **SongFolder** line didn't help either `[01:59:30][Warning] Can't run ScanFiles, "D:\Users\nut573\Desktop\songs"`

**Comment by Dan9er** [comment]
Try using forward slashes (/), not backslashes (\\). People mix those up in file paths all the time.

**Comment by Drewol** [comment]
The only way I can make this error happen myself is to point to a folder that doesn't exist.

Backslashes should work and they are actually the default path separator on windows.

`SongFolder = "\songs"` does not work but `SongFolder = ".\songs"`  or just `SongFolder = "songs"`  should work.

**Comment by nut573** [comment]
Okay I just extracted a new copy of the game, and now it worked right away. Very strange. The only thing I did differently was drag my songs folder in before launching the exe for the first time.

**Comment by nut573** [comment]
Okay so it turns out the cause of it was actually from editing the cfg in Wordpad. If I use Notepad instead, it works fine.

**Comment by Dan9er** [comment]
\>Wordpad

Gonna have to add the fact that you have to use Notepad in the README. PR incoming!
