### ISSUE TITLE
[Bug?] Keys don't get registered right after the song is loaded

### ISSUE THREAD

**Issue by hw4n** [Drewol/unnamed-sdvx-clone#300]
Keys don't get registered right after the song is loaded.
You can try to reproduce following the steps below:

1. start playing any song
2. spam any button: bt-a, b, c, d or fx-l, and fx-r
3. you will notice the blank moment where keys don't get registered

Any key should be registered even if the song did not begin yet.

In my opinion, keystrokes should be always displayed since in sdvx, and kshoot doesn't have this issue, not being able to spam keys at start of the song.

**Comment by hw4n** [comment]
I've tried this on the latest build too

**Comment by Hinara** [comment]
Is it on a specific track ? Which version do you use ?

**Comment by Hinara** [comment]
Ah ok effectively there is a little gap where key are effectively not shown as pressed just before the audio from the track start to play
