### ISSUE TITLE
[Bug] some chart with very long that can't play

### ISSUE THREAD

**Issue by MasterCelebi** [Drewol/unnamed-sdvx-clone#308]
**Describe the bug**
When I play the chart, it return to song select immediately

**To Reproduce**
1. Go to Start
2. Click on "Celebi Mix No.05"
3. After click start game return to song select immediately

**Expected behavior**
USC should can play every chart if longer chart take longer loading map is fine.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - GPU: NVIDIA GeForce GTX 1050 Ti
 - CPU: i5-8300H
 - Version: Git commit: 2020-02-08_2361f14

**Additional context**
About lane tits : make it quicker spin like old version
"https://drive.google.com/file/d/1-B2weR0sHCcJ5RpH7iqMCbFegWGVrwbM/view?usp=sharing"
and song file it big because song is very long

**Log file**
[log_usc-game.exe.txt](https://github.com/Drewol/unnamed-sdvx-clone/files/4328755/log_usc-game.exe.txt)
Song I play is "Celebi Mix No.05"

**Comment by Hinara** [comment]
```
[11:38:06][Error] Invalid buttons at line 61894
[11:38:06][Info] Finished task "Load KShootMap" in  5327 ms
[11:38:06][Warning] Invalid map format
```

**Comment by Hinara** [comment]
This is caused by some spaces on this line.

**Comment by MasterCelebi** [comment]
ok I will fix this part if it still not work how to see log like this I can't see this in my log

**Comment by MasterCelebi** [comment]
Problem solve!!!
