### ISSUE TITLE
Assert fails with some beatmaps that use beat denom not equal to 4

### ISSUE THREAD

**Issue by dsonck92** [Drewol/unnamed-sdvx-clone#31]
While trying out different ksh maps I sporadically got crashes. After building the debug version and attaching a debugger, it turned out that the assert(denom % 4 == 0) failed. This was because the file in question switches to 5/6 after some time in the song. Maybe this should be implemented.

I'm not sure if there is a reason the denom needs to be a multiple of 4.

**Comment by Dan9er** [comment]
* What commit were you using?
* Where is the log file?

**Comment by Drewol** [comment]
@Dan9er doesn't matter, this is in all versions and the log isn't needed. It would be nice if @dsonck92 could send me the chart file that has this so i can test if anything breaks when i remove the assert.

**Comment by dsonck92** [comment]
https://drive.google.com/file/d/0B2VFMVQoncWIaU1qeUI2YS1VNkk/view

This is the zip containing the chart. It's in folder 22/[PUCific] Mdrqnxtagon
