### ISSUE TITLE
[Bug] Charts not encoded with UTF-8 have broken font rendering

### ISSUE THREAD

**Issue by scatterfish** [Drewol/unnamed-sdvx-clone#314]
**Describe the bug**
Foreign characters in charts using encodings other than UTF-8, such as SJIS and ISO-8859-15, are rendered incorrectly by the game.

**To Reproduce**
1. Obtain a chart using non UTF-8 encoding (old KSM packs have many)
2. Observe incorrect character rendering of foreign characters

**Expected behavior**
Fonts are rendered the same as if the charts were encoded in UTF-8.

**Screenshots**
Charts using non UTF-8 encoding:
![image](https://user-images.githubusercontent.com/10539472/77837206-80b7f900-7134-11ea-9e76-4f336786c76f.png)
Charts using UTF-8 encoding:
![image](https://user-images.githubusercontent.com/10539472/77837224-b4931e80-7134-11ea-8b06-a8a64aacc8bd.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - GPU: Intel UHD Graphics 630
 - CPU: Intel i7-8750H
 - Version: 2020-03-26_616af50

**Additional context**
I am making a PKGBUILD for this game, and build of the game seen in the screenshots are from it. I doubt that has any impact on the issue.

**Log file**
Nothing seems to be logged about these alternate encoding issues.

**Comment by 123jimin** [comment]
I'm currently experimenting with implementing encoding detection for USC.
Would you provide some examples for me to test?

**Comment by scatterfish** [comment]
[This song pack](https://mega.nz/#!sohCmKya!i_FohRoetuuAWy6JFQpHFJe0Yv7OTHqdrVCmYK8et0c) is where I found the examples above. Most charts are UTF-8 but many are Shift_JIS and ISO-8859-15.

**Comment by 123jimin** [comment]
![2020-05-23_203031_usc-game_Debug](https://user-images.githubusercontent.com/835369/82729674-4e8dd680-9d34-11ea-9872-5ce8e7ec53fe.png)

I made an experimental fix for this problem, but all charts you gave seemed to be in either UTF-8 or SHIFT_JIS.
Would you provide a chart which is encoded with ISO-8859-15, or any other encoding which is not UTF-8 or SHIFT_JIS? (If there is one among charts you gave, then that means I need some more work on encoding detection)

**Comment by scatterfish** [comment]
As it turns out, you're absolutely correct. My text editor had identified the charts for some songs (such as "phi", "overclock", and "mugenkairou") as ISO-8859-15 but there seems to be some strangeness about them. Using Mozilla's universal character encoding detector, it reports them as either Windows-1252 or simply unknown, yet when forcing my text editor to interpret them as Shift_JIS they are displayed correctly.

As for why this could be, I have no idea, but it's probably not relevant to this fix.
