### ISSUE TITLE
[Bug] FIltering by folder not working when using "-gamedir"

### ISSUE THREAD

**Issue by Nanoblender** [Drewol/unnamed-sdvx-clone#318]
When I launch the game with the option `-gamedir=` and go to the song selection menu, all the songs are there but the filter option is not working, it doesn't give the ability to choose a folder

I am running the game on linux

**Comment by scatterfish** [comment]
Confirmed this bug also occurs without `-gamedir=`. It happens any time the executable is run while the current working directory is not the executable's directory.

**Comment by scatterfish** [comment]
Configuring the song folder to an absolute path instead of relative one fixes the issue, which suggests the cause of the issue is this: https://github.com/Drewol/unnamed-sdvx-clone/blob/master/Main/src/SongSelect.cpp#L1010
