### ISSUE TITLE
TC+ Analogue input inverted

### ISSUE THREAD

**Issue by Chris-SG** [Drewol/unnamed-sdvx-clone#32]
ie. right knobs require left movement and vice-versa. Perhaps have an option to support axis flipping?

(not sure if this is just with my controller, however actual system mouse movement works as expected, so it is only in-game).

**Comment by Drewol** [comment]
does the knobs move the wrong cursor or does the turning go in the wrong way?

If the knobs are moving the wrong cursor then you just have to swap the `Controller_Laser0Axis` and the `Controller_Laser1Axis` settings in the config file. If they are turning the wrong way then you can try setting the sensitivity to a negative number for now.

**Comment by Chris-SG** [comment]
Yeah, they are going the wrong way. Didn’t think of using negative sensitivity, thanks!

**Comment by Drewol** [comment]
Alright, glad it worked though I should probably add an option to flip the inputs in the future anyway
