### ISSUE TITLE
Hope the judgment can be more sensitive

### ISSUE THREAD

**Issue by wz18207** [Drewol/unnamed-sdvx-clone#320]
When playing with a hand platform,  faced with a score of 16 points or 24 points of interaction, the game may not possible to correctly identify.
I hope the game is more sensitive in the judgment, and the judgment interval for the second note after the first note is determined can be shorter

**Comment by Drewol** [comment]
Hi, I am having trouble understanding what you mean, could you try explaining it more in detail? Maybe some images would help.

**Comment by ultrakiller2** [comment]
He probably tries to say that he wants a less lenient (more strict) judge
I opened a similar issue before: #130

**Comment by wz18207** [comment]
![Snipaste_2020-04-20_00-48-18](https://user-images.githubusercontent.com/47554726/79694152-3217fd80-82a1-11ea-9335-cc0637570c21.png)
![Snipaste_2020-04-20_00-45-55](https://user-images.githubusercontent.com/47554726/79694161-3d6b2900-82a1-11ea-91e9-9cb375537c6d.png)
like these,it's easy to break combo when i press equal to these key numbers. could please short the time interval of each keys.
