### ISSUE TITLE
[Feature] Allow us to hide the autoplay

### ISSUE THREAD

**Issue by pohihihisocks** [Drewol/unnamed-sdvx-clone#321]
**Is your feature request related to a problem? Please describe.**
I want to record gameplay's of my map and I don't want the autoplay text on top of the screen ui

**Describe the solution you'd like**
remove or give an option to hide the autoplay text

**Comment by Drewol** [comment]
You can remove it from the skin file https://github.com/Drewol/unnamed-sdvx-clone/blob/master/bin/skins/Default/scripts/gameplay.lua#L288

**Comment by pohihihisocks** [comment]
Ah yes thank you lol
