### ISSUE TITLE
Song Collection Recoverer after changing SongFolder path.

### ISSUE THREAD

**Issue by Tom0129** [Drewol/unnamed-sdvx-clone#337]
Hello,
[edited 2020-06-18] More details about how to reproduce.
If we change the "SongFolder" parameter in "Main.cfg" with a new path, Maps.db do something weird and we lose all our songs saved in custom Collections.

usc-db-recoverer.exe don't recover **collections songs** because my old path seems hardcoded : "Collection entry to [COLLECTION_NAME] lost, no song at E:\ProgramFiles\ks\songs\[...]"

"E:\ProgramFiles\ks\songs\" is my old path.
It should check at the new path, ex. "C:\USC\songs".

![Sans-titre-1](https://user-images.githubusercontent.com/16181727/82592513-549f7e00-9ba1-11ea-9ec9-82aede98f9fa.jpg)

How to reproduce : (save your Maps.db before)
"SongFolder" path in "Main.cfg" is "E:\wooshgame\songs" and we have one Collection named "test" with 10 songs inside.
- We edit the path with another location : "E:\USC\songs"
- We move the song folder at this new location
- We launch the game, it finds all songs, scores, and collections

I expect my "test" collection to have 10 songs inside.
Problem : my "test" collection is empty.

Maps.db don't seems to be affected (the size don't change) but if I reverse and get back to my previous setup, my collections are still empty. I need to setup my "Maps.db" backup to get everything works.

It's not a big issue, but I'm stuck with my path and can't change it without losing my collections.

**Comment by Tom0129** [comment]
> If you are on the latest database, scores are saved based on the chart hash. After rebuilding the index for the new song path, your scores should still be connected to the correct charts (assuming you didn't modify the actual charts as well)

Thank you for your interest.
I have no problem for re-importing scores, it works really well.

My main concern is : if we change the song's folder path, we lose all the songs saved in the custom collections.
Since the path seems hardcoded, all my collections are there, but empty.

**Comment by itszn** [comment]
@Tom0129 I made a site to help convert old paths https://itszn.github.io/usc_db_tool/index.html

Open your maps.db with the old paths, then click fix paths. It will try to guess the old path, but you can enter w/e it was. Then enter the new path you want to change it to. Finally download the db and replace

(make a backup of your db before trying please :)

**Comment by Tom0129** [comment]
> @Tom0129 I made a site to help convert old paths https://itszn.github.io/usc_db_tool/index.html
> 
> Open your maps.db with the old paths, then click fix paths. It will try to guess the old path, but you can enter w/e it was. Then enter the new path you want to change it to. Finally download the db and replace
> 
> (make a backup of your db before trying please :)

Many many many many thanks !
I made a quick test, it worked like a charm.

The path's guess was good, and the find&replace did his job.
I know we're not supposed to switch our SongPath everyday but you saved me there, really.
Thank you again.

**This tool should be highlighted somewhere :)**

![Capture](https://user-images.githubusercontent.com/16181727/85231633-45f2f380-b3f9-11ea-8d21-a4fee71d3be4.PNG)

Best Regards,
