### ISSUE TITLE
Keyboard mapping buttons are too simple

### ISSUE THREAD

**Issue by dsonck92** [Drewol/unnamed-sdvx-clone#35]
While the key mapping settings work, they are severely lacking.

- The buttons do work but you can't see if the mapping succeeded. This might not seem that important but it's useful to see that at least an key ID is assigned (much like the original kshootmania did)
- There is no feedback about adding secondary buttons (which is apparently supported)

These two things caused the following issue for me: I had assigned all my buttons, but decided to remap them. Some keys from my old mapping were reused as different buttons in my new mapping. After mapping, it turned out that I had set both the normal and alt keymapping, causing 2 game buttons being pressed on a single keypress. While it would be nice to prevent this kind of double mapping, it would be even nicer to be able to indicate whether you want to redefine the normal or alt key. And show how they are mapped.

**Comment by Drewol** [comment]
I've changed it so it says which key is bound in 2efe3e97ecc9073dd4433f69655984f062e01153 but you still can't bind secondary keys. The key display works but it doesn't look great for some keys, will look into changing it in the future.
