### ISSUE TITLE
[Bug] missing dll after running updater (libiconv-2.dll)

### ISSUE THREAD

**Issue by firinael** [Drewol/unnamed-sdvx-clone#350]
**description**
after running updater.exe normally, it concluded with the message "The code execution cannot proceed because libiconv-2.dll was not found. Reinstalling the program may fix this problem.", re-running the updater causes this to repeat, even when in admin mode, and running the game itself also causes this error to pop up.

**reproduction**
- run updater.exe;
- that's it, I guess.

**screenshot**
![image](https://user-images.githubusercontent.com/67032657/84843680-effc0580-b01e-11ea-9158-b366296a5634.png)

**configs**
 - OS: Windows 10 Pro (1909, x64);
 - GPU: GTX 1060;
 - CPU: Ryzen 5 1600;
 - Version: 0.4.0 - git commit 2020-06-10_a41f2adc.

**Comment by Drewol** [comment]
I'm not sure why some users have started getting this but it appears you can make it work by renaming the existing `libiconv.dll` to `libiconv-2.dll`

**Comment by firinael** [comment]
had to copy the existing `libiconv.dll` and name the copy `libiconv-2.dll` (needed both, it seems), but that did work.

thanks a ton!

I've been seeing some missing icons (a square with an X inside it) in-game, maybe it has something to do with that? (just going off of the name, I've no idea what those files *actually* do)
