### ISSUE TITLE
[Bug] Lua Error after fixing the libiconv-2.dll bug

### ISSUE THREAD

**Issue by bimsboy** [Drewol/unnamed-sdvx-clone#351]
**Describe the bug**
The problem happens when i try to fix the libiconv-2.dll error by renaming the libiconv to libiconv-2. 
After renaming the libiconv file to libiconv-2, the bug says i dont have the libiconv file. So i copy the file and now i have two libiconv file in the same folder like below:

![image](https://user-images.githubusercontent.com/49588484/84982353-ba5f3580-b160-11ea-8ea6-9553a9e4e784.png)

The game start opening but after waiting for like 2 minutes with blank white screen the error happened again but with different message says that common.lua file in the skin folder is missing:

![image](https://user-images.githubusercontent.com/49588484/84982486-07dba280-b161-11ea-9c71-25faf869a8da.png)

Then, i check my default skin folder, turns out i have the skin but i still cant play the game the error still pop up with the same message like above.

**reproduction**
copy libiconv.dll and renamed it to libiconv-2.dll to fix the dll error
run updater.exe;

**Desktop:**
 - OS: Windows 10
 - GPU: GT 755M
 - CPU: i7-4700 MQ
 - Version: 0.4.0 - git commit 2020-06-10_a41f2adc.

**Log file**

[log_usc-game.exe.txt](https://github.com/Drewol/unnamed-sdvx-clone/files/4796499/log_usc-game.exe.txt)

Thank you...

**Comment by 123jimin** [comment]
Seems that USC is not working correctly because of non-ASCII character (C2, A0) in the pathname.
This seems to be unrelated to libiconv, but it should have already been resolved (#332)...

1. What's the full pathname which the folder `USC Sound Voltex` is located under? (Especially the folder under `Desktop`)
2. What's the codepage you're using? (This can be known by typing `chcp` in the command window. The command window can be opened by pressing Win+R key then entering `cmd`.)

**Comment by bimsboy** [comment]
1. Is the issue resolved by moving the game directory under different path, where all folders' names only contain alphabets, numbers, and blanks?
I move my game to: C:\Games\USC Sound Voltex
The issue is still happening even tough i only have the default skin

3. What's the codepage you're using? (This can be known by typing chcp in the command window. The command window can be opened by pressing Win+R key then entering cmd.)
My active code page is: 437

**Comment by 123jimin** [comment]
I found the following problem in the code:
- The skin file is not loaded properly when it's located under a directory with non-ASCII character
- The `luaL_dofile` function doesn't accept pathnames encoded with UTF-8 (fortunately only three places are using this)

However, this problem should be gone when the pathname which the binary or the skin is placed under does not contain any non-ASCII name.
1. Have you tried updating USC _after_ the game is moved under the path?
2. Could you provide the log file after re-updating USC?
3. Does the skin file mentioned in the error popup exist?
