### ISSUE TITLE
[Bug]Long Notes can be combo-ed even it is released shortly in the middle.

### ISSUE THREAD

**Issue by Derrick97** [Drewol/unnamed-sdvx-clone#355]
**Describe the bug**
I'm not sure this is intended or not but the combo does not break when release the long note very shortly and then hold it again. From the sdvx cab, this can not happen, as the combo breaks whenever the long hold is dropped, even for a very short time. If allowing shortly release long note in the middle without combo break, this may allow smashing in some LN heavy songs, such as veRtrageS[EXH], and make their score not as qualified as the score on cab.

**To Reproduce**
Pick any song that has a very long note. For example, Got More Raves[HVN] or veRtrageS [EXH]. When hitting LN, instead of holding it, hit the correct button quickly (eg. Pretend their is a long jack on that button), or just simply release and then press it again quickly. For the veRtrageS[EXH], at the first LN part (which is very hard on the cab), you can even hold a the buttons first. When the new LN is coming, simply release all the buttons and than press it again. You can easily combo(or should I say smash) the LN part without much effort and almost no sightreading. The current timing window that allows the LN can be combo-ed between releasing it and press it again is extremely wide.

**Expected behavior**
I suggest introduce combo break if the player fails to hold the long note throughout its entire length even the player tries to save it by holding that note again quickly(except the very ending when there is actually no combo), or at least reduce the allowed release time. This will prohibited smashing on heavy LN patterns without single notes, and make the score of a lot of the LN heavy songs more reliable.

**Desktop (please complete the following information):**
 - OS: Windows10
 - GPU: NVIDIA GTX 1060
 - CPU: i7 2600k
 - Version: The latest till the day of this post.

**Comment by 123jimin** [comment]
I confirmed it by trying the strat on BLACK or White EXH on konasute and USC. However, "the combo breaks whenever the long hold is dropped" part is not true. It's just that the window is very, _very_ narrow on konasute compared to USC.

There are a few other issues related to long note ticks, and to resolve them more through understanding of long note ticks is required.

**Comment by 123jimin** [comment]
![image](https://user-images.githubusercontent.com/835369/85913911-eb7fea00-b873-11ea-8e55-8561969c1c16.png)

On konasute, I've been testing on a chart with low BPM (100BPM), and it is evident that letting the button go does not correspond to missing long notes. I'm suspecting that the button needs to be held exactly when the tick happens.

**Comment by 123jimin** [comment]
![image](https://user-images.githubusercontent.com/835369/85916795-00b64200-b88f-11ea-8edb-bf22e49dff73.png)

Hypothesis:
1. When each tick is being passed, the button must be held for the moment.
2. However, the last tick will be counted as long as the release happens after `end of the long note - near window`.

Currently there are three issues related to long notes:
- Judgement of long notes are too generous when the button is released for a moment, during processing the long note. (This issue)
- Judgement of long notes are too _strict_ when the button is released a little bit earlier.
- For certain cases, long note which should not be counted because of button not being pressed sufficient times will be counted

**Comment by Derrick97** [comment]
Thanks for your thorough investigation, I really really appreciate it. Hopefully this can be fixed in the next version. I won't post the scores of any more Long Note Heavy songs until this is fixed.
