### ISSUE TITLE
Unable to build latest on Windows [Bug]

### ISSUE THREAD

**Issue by Fluzzarn** [Drewol/unnamed-sdvx-clone#358]
**Describe the bug**
When trying to clone and setup master on Windows, there is an error involving iconv. Installing the package via vcpkg gives unofficial-iconv and CMake fails to pick it up.

**To Reproduce**
1. Clone master on a machine without any dependencies already installed
2. Install all dependencies in build.windows through vcpkg
3. Run GenerateWin64ProjectFiles.bat

**Expected behavior**
The script is successful and the Visual Studio SLN files are created

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU: GTX 1060ti
 - CPU: i7 6700k
 - Version: master/ commit  26d8d60 

**Additional context**

**Log file**
C:\Users\Dan\usc-mp\unnamed-sdvx-clone>..\vcpkg\vcpkg.exe install libiconv:x64-windows
Computing installation plan...
The following packages are already installed:
    libiconv[core]:x64-windows
Package libiconv:x64-windows is already installed

Total elapsed time: 1.064 ms

The package libiconv:x64-windows provides CMake targets:

    find_package(unofficial-iconv CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::iconv::libiconv unofficial::iconv::libcharset)

C:\Users\Dan\usc-mp\unnamed-sdvx-clone>.\GenerateWin64ProjectFiles.bat
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19041.
CMake Error at C:/Users/Dan/usc-mp/vcpkg/installed/x64-windows/share/Iconv/vcpkg-cmake-wrapper.cmake:3 (_find_package):
  By not providing "FindIconv.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Iconv", but
  CMake did not find one.

  Could not find a package configuration file provided by "Iconv" with any of
  the following names:

    IconvConfig.cmake
    iconv-config.cmake

  Add the installation prefix of "Iconv" to CMAKE_PREFIX_PATH or set
  "Iconv_DIR" to a directory containing one of the above files.  If "Iconv"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  C:/Users/Dan/usc-mp/vcpkg/scripts/buildsystems/vcpkg.cmake:370 (include)
  CMakeLists.txt:55 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/Users/Dan/usc-mp/unnamed-sdvx-clone/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Dan/usc-mp/unnamed-sdvx-clone/CMakeFiles/CMakeError.log".

**Comment by itszn** [comment]
You have to use cmake 3.12 or later since it ships with the `FindIConv.cmake` file
