### ISSUE TITLE
Two Issues

### ISSUE THREAD

**Issue by AKAMER9** [Drewol/unnamed-sdvx-clone#359]
The first issue is whenever I launch the game it takes about two-three minutes before opening and the second is that it crashes frequently.

This happens regardless of if I'm using the default skin or a custom skin and I have tried uninstalling and reinstalling the game twice, also I'm using the prebuilt version of the game.

**Comment by Drewol** [comment]
Could you provide some more info, such as the log file from the game and your system specs?

**Comment by AKAMER9** [comment]
I ran the updater and now it works fine I didn't try that because I figured reinstalling would have the same effect, sorry for the inconvenience.

**Comment by Drewol** [comment]
Ok, I'll close this issue for now then
