### ISSUE TITLE
[Bug] Skins including Korean character directories makes lua cannot open file error.

### ISSUE THREAD

**Issue by hyeonsoft** [Drewol/unnamed-sdvx-clone#364]
**Describe the bug**

**To Reproduce**
1. Save skin file in Korean filename directories.
2. `[Warning] Lua error: cannot open C:\Korean directory names\bg.lua: Illegal byte sequence` occurs.

**Expected behavior**
The skin should be loaded.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU: 
 - CPU: i5 - 8265U
 - Version: 0.4.0
 - Git commit: 2020-07-11_7d82af1f

**Additional context**

**Log file**
If applicable, attach the log file or paste a snippet of it.

**Comment by 123jimin** [comment]
I believe that this issue should be resolved when the PR #354 is merged.
Also see issue #351

**Comment by Drewol** [comment]
This should be resolved now with the merge of #354 please reopen if the issue persists.
