### ISSUE TITLE
[Bug] Selected song isn't visible on ultrawide resolutions

### ISSUE THREAD

**Issue by kstark** [Drewol/unnamed-sdvx-clone#369]
**Describe the bug**
For ultrawide resolutions (e.g. 3440x1440, or 21:9 aspect ratio), the song select menu allows you to scroll to the 3rd row of songs without scrolling the page down.

**To Reproduce**
This can reproduced in windowed mode without needing an actual ultrawide monitor.
1. Resize the game window to a roughly 21:9 aspect ratio
2. Go to song select
3. Scroll until a song on the 3rd row is selected
4. Observe that as you scroll down, the selected song is out of view

**Expected behavior**
I would expect the song select list to ensure that the selection is always visible on screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/1867759/88243527-85ee0600-cc45-11ea-866e-b3ac35875f7b.png)

**Desktop (please complete the following information):**
Mostly N/A but Windows, `Git commit: 2020-07-20_b1e24dd3`

**Comment by hyeonsoft** [comment]
It may be a skin problem, not the problem of usc.

Have you tested default skin?

**Comment by kstark** [comment]
🤦 good point - default skin has a centered selection so this doesn't occur, definitely a skin issue. Thanks!
