### ISSUE TITLE
[Bug] Mac OS building error

### ISSUE THREAD

**Issue by SangsterMLG** [Drewol/unnamed-sdvx-clone#372]
**Describe the bug**
When I am installing sound vortex on MacOS 10.15.6, a CMAKE error occurs saying an error occurs. 
P.S. Please tell me what you mean by: "and then 'make' from the root of the project" I'm still a beginner at terminal stuff

**To Reproduce**
1. Follow the clone steps until Step 2 on MacOS
2. Run the command "sh (directory of the sh file for installing)"

**Expected behavior**
There shouldn't be an error, and there should be a executable file in the "bin" folder in the root of the cloned folder, however it does not appear

**Screenshots**
![Screen Shot 2020-07-29 at 9 17 56 PM](https://user-images.githubusercontent.com/48872975/88799325-41cca980-d1e1-11ea-8483-45062c3a42ef.png)

**Desktop (please complete the following information):** (The full Mac is a Macbook Air 13 inch base model from 2017)
 - OS: [e.g. Windows, Linux, Mac] MacOS 10.15.6
 - GPU: [e.g. GTX 1050, RX 570] None
 - CPU: [e.g. i7 2600k, Ryzen 7 3700x] 1.8 GHz Dual-Core Intel Core i5
 - Version: [e.g. 0.4.0 or Git commit: 2019-12-18_c98c505] (found in log)

**Additional context**
None

**Log file**
If applicable, attach the log file or paste a snippet of it.
[CMakeError.log](https://github.com/Drewol/unnamed-sdvx-clone/files/4994775/CMakeError.log)
[CMakeOutput.log](https://github.com/Drewol/unnamed-sdvx-clone/files/4994776/CMakeOutput.log)

**Comment by Drewol** [comment]
Have you run `git submodule update --init --recursive` ? And for running `make` it means to simply just type and run that command from the terminal. However it should be possible to use the prebuilt game from http://drewol.me/Downloads/Game_mac.zip after installing the Brew packages

**Comment by SangsterMLG** [comment]
There was a prebuilt game? I didn't know! i downloaded it, how do I run the "usc-game" file?

**Comment by Drewol** [comment]
I think you need to command + right click it or something like that since it's considered as some random program from the internet

**Comment by SangsterMLG** [comment]
It shows up as a plain text file and opens up in TextEdit...

**Comment by SangsterMLG** [comment]
I was able to fix it! The archiving program was the problem, I used a better one and It unzipped perfectly, and it works! Tysm
