### ISSUE TITLE
charts ends abruptly in the middle

### ISSUE THREAD

**Issue by UandWhatArmy** [Drewol/unnamed-sdvx-clone#390]
i am having an issue on certain charts where in the middle of playing, it displays track completed and goes to the score screen.  it happens in the same place every time.

**Comment by 123jimin** [comment]
1. Does the song (the audio file) ends before the chart ends?
    - The gameplay ends when the end of the audiofile is reached.
    - This is an undesirable behavior, but it requires some work to fix this issue.
2. If not, then it's likely a bug which needs to be fixed.
    - Could you provide the chart (or DL link) you're having problem with?

**Comment by UandWhatArmy** [comment]
I just looked at the song files and for the versions I was having issues with, the song file is cut short and I have no clue why.  Thank you for your help.
