### ISSUE TITLE
[Bug] Building on Ubuntu MATE 20.04, make fails due to error in Application.cpp

### ISSUE THREAD

**Issue by Th3rdEye** [Drewol/unnamed-sdvx-clone#397]
As the title suggests, I am building from source on Ubuntu MATE 20.04. I have added all the necessary packages and the third-party submodules, and everything went well until the final "make" command. Here is the output of the terminal:

[ 80%] Built target Beatmap
[ 80%] Building CXX object Main/CMakeFiles/usc-game.dir/src/Application.cpp.o
/home/th3rdeye/Downloads/unnamed-sdvx-clone-master/Main/src/Application.cpp: In member function ‘bool Application::m_Init()’:
/home/th3rdeye/Downloads/unnamed-sdvx-clone-master/Main/src/Application.cpp:634:59: error: expected primary-expression before ‘)’ token
  634 |  Logf("Git commit: %s", Logger::Severity::Info, GIT_COMMIT);
      |                                                           ^
make[2]: *** [Main/CMakeFiles/usc-game.dir/build.make:82: Main/CMakeFiles/usc-game.dir/src/Application.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1021: Main/CMakeFiles/usc-game.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

**Steps to reproduce the behavior:**
I downloaded all the libraries listed on the build.linux file without issue. I did not see the `git submodule update --init --recursive` on the GitHub page, so I manually downloaded all third-party folders from their respective GitHub pages. Not sure if this makes a difference or not since `cmake -DCMAKE_BUILD_TYPE=Release .` did not throw an error. `make` stops at 80% complete with the error message above.

**Expected behavior**
I have never built this before so I'm not sure of what the expected behavior is. I assume it goes to 100% completion and throws no error like when installing the rest of the libraries.

**Screenshots**
If screenshots are needed, then I will provide. However, this is all done in the terminal so text should suffice.

 Done with version 0.4.0, commit 8445ddf

As I am relatively new to Linux, please let me know if I missed something obvious. Thanks!

**Comment by Drewol** [comment]
Could you open `Main/src/Application.cpp` in an editor and check that line 634 only contains `Logf("Git commit: %s", Logger::Severity::Info, GIT_COMMIT);` and nothing else? The error makes it seem like the file has accidentally been edited.

**Comment by Th3rdEye** [comment]
Yes, it has just that line and nothing else.

**Comment by itszn** [comment]
I have had this in the past, it is very likely that GIT_COMMIT is not defined. You could just comment out that line and see if that works

**Comment by Th3rdEye** [comment]
Alright, that works. Thanks!
