### ISSUE TITLE
Songs launch twice when manually binding start to "enter"

### ISSUE THREAD

**Issue by okand** [Drewol/unnamed-sdvx-clone#4]
Assuming this isn't some weird thing only I get it should be fairly obvious. Making an issue just in case and for the sake of documentation.

Whenever I launch a song it starts twice and slightly out of sync. You can hear it and see it when the track tilts. Pressing escape stops one of them and you can still hear the other one when looking at the results screen. Pressing escape again then puts you back into the game with only one instance of the song playing.

**Comment by Drewol** [comment]
I believe this happens when you bind start to enter, which already is start by default. Though this is a bug and will be fixed

**Comment by okand** [comment]
Confirmed!

Binding start to another key prevents this from happening while enter still also functions as start.
Thank you.

**Comment by Dan9er** [comment]
I'm gonna reopen (@okand, please remember to close your issues if they are resolved) this because I don't think that the Enter keybind should be hardcoded.

@Drewol, since you are the owner of this repo you should be able to change the title of this issue to something more informative.

**Comment by okand** [comment]
I’m pretty sure I just commented and didn’t hit the close button precisely because it’s still an issue in the game. Just mentioned working around it worked.
