### ISSUE TITLE
[Bug] Editor option "Standard BPM of HiSpeed" seems to not work

### ISSUE THREAD

**Issue by Anonymeister** [Drewol/unnamed-sdvx-clone#401]
Hello. Today, I was working on a chart and I tried making it have the gimmick of starting off at halved HiSpeed and going up to a regular amount later, and to do this I set the "Standard BPM of HiSpeed" amount to the correct double amount. However, when I play on USC, it seems to ignore that and use the "default" option instead, which is the halved BPM, so it just doubles instead of normalizes when the BPM change kicks in. While this is a very rarely used feature of USC, I'd prefer it being fixed so these issues don't happen in the future.

**Comment by Anonymeister** [comment]
if it helps, the value in the ksh that KSM puts the "Standard BPM" under is "to", right below "t" (the BPM range)

**Comment by Drewol** [comment]
Added in df7b3b5ba22bd6295f55c451dd8d4600c447e239
