### ISSUE TITLE
usc.exe deleted itself after closing the game

### ISSUE THREAD

**Issue by popcornic420** [Drewol/unnamed-sdvx-clone#407]
After playing USC for a few minutes, I closed the game. Moments later, I returned and found that the program was "moved, replaced or deleted" and thus I had to remove the pinned icon on my taskbar. I checked the files and saw that usc.exe was gone. I then reinstalled and moved everything. My scores were wiped but that's fine, the game worked. Until I closed it again. It deleted itself. I ran the updater.exe and it installed all the .dll other files but not usc.exe itself. Then, updater.exe was gone.

I expected USC to not delete itself. Before today's report, it has never shown any unusual behaviour.

 - OS: Windows
 - GPU: GTX 1050
 - CPU: i7-8750H 
 - Version: 0.4.0, Git commit 2020-10-31_a4b072c5

[log_usc-game.exe.txt](https://github.com/Drewol/unnamed-sdvx-clone/files/5584380/log_usc-game.exe.txt)

**Comment by Drewol** [comment]
Check your antivirus or windows defender logs.

**Comment by lyxlovelyx** [comment]
Maybe it was deleted by antivirus software

**Comment by popcornic420** [comment]
Indeed it was my antivirus software that caused the issue. Thank you for your quick responses, I will now close the issue.
