### ISSUE TITLE
Linux builds without any timing values

### ISSUE THREAD

**Issue by farkasma** [Drewol/unnamed-sdvx-clone#420]
Building on Manjaro from the AUR's git branch. The game ends up having no timing values (they're all 0). Going to the settings and clicking the "Set to NORMAL" button inputs all the righ things, but it may not be obvious for first time users. And it's just odd anyway.

**Comment by itszn** [comment]
Thanks for the report! I think this is an exceptional case (normally it should use a default value) and might be somehow related to the build process on your machine.

If you want to send the `usc-game` binary my way, I can take a look at it and see if I can figure out what went wrong.

**Comment by farkasma** [comment]
This is the one, where I already fixed the values, if you want a clean one I can rebuild it for you.
[binary.zip](https://github.com/Drewol/unnamed-sdvx-clone/files/5783887/binary.zip)

**Comment by itszn** [comment]
Thanks I figured out it was some compiler undefined behavior and it should be fixed in the latest commit
