### ISSUE TITLE
linker issue (cannot produce executable)

### ISSUE THREAD

**Issue by A0MASA** [Drewol/unnamed-sdvx-clone#423]
I'm currently trying to run the game on macOS, but theres an issue producing the executable along with a bunch of warnings.  `make` fails at 91% with this error:

>[ 91%] Linking CXX executable ../bin/usc-game
Undefined symbols for architecture x86_64:
  "GameConfig::VERSION", referenced from:
      Application::m_LoadConfig() in Application.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/usc-game] Error 1
make[1]: *** [Main/CMakeFiles/usc-game.dir/all] Error 2
make: *** [all] Error 2

I've ran `git submodule update --init --recursive`, and I've installed all the deliverables.

I've also tried macOS 10.12 but no luck.

Desktop
 - OS: Mac 10.11.6
 - GPU: Intel HD Graphics 4000
 - CPU: Intel Core i7
 - Version: 0.4.0

I've also attached the log for the warnings

thanks in advance

[linker error (USC).log](https://github.com/Drewol/unnamed-sdvx-clone/files/5856094/linker.error.USC.log)

**Comment by Hinara** [comment]
Ok so I already looked a bit for the source of this issue.
The issue seems to be that mac's clang doesn't like that VERSION is in the header file, and seems to discard it.
https://github.com/Drewol/unnamed-sdvx-clone/blob/master/Main/include/GameConfig.hpp#L219
constexpr on member implies inline but inline on static member variable is guaranteed only since C++17.

**Comment by Hinara** [comment]
Try PR #424 If it does not fix your issue, try #425.
If #424 fix your issue then we will go with this one, if not well #425 move some field initialization in source file which is quite bothering.

**Comment by A0MASA** [comment]
godlike, 425 worked. thanks for the help 

running the executable produces a couple errors but so far I haven't ran into any game breaking problems.

**Comment by Hinara** [comment]
#424 didn't worked for you ?

**Comment by A0MASA** [comment]
[linker error (USC 424).log](https://github.com/Drewol/unnamed-sdvx-clone/files/5891648/linker.error.USC.424.log)
[linker error (USC 425).log](https://github.com/Drewol/unnamed-sdvx-clone/files/5891649/linker.error.USC.425.log)
[linker error (USC 425 after running).log](https://github.com/Drewol/unnamed-sdvx-clone/files/5891650/linker.error.USC.425.after.running.log)

**Comment by A0MASA** [comment]
only noticeable problem is nautica doesn't work

**Comment by Drewol** [comment]
So #425 should be merged or do you want more tests @Hinara ?

**Comment by Hinara** [comment]
Sorry I was not available ^^" 
So It would be better that #424 work as I think it might be easier to manage VERSION in the hpp file, but it is really strange what does A0MASA's compiler do it accept constexpr without doing anything with it :/ Seems partially a compiler issue.
I'm gonna remove constexpr from VERSION and hope that it will work on A0MASA's compiler
In any case if you think that the solution in cpp file is good enough you can merge it. But if you prefer to keep VERSION in the hpp I've remove the constexpr from the hpp so if @A0MASA can try with this new version of #424.

**Comment by Hinara** [comment]
Well no response in a month, so I think you should take #425 as it is sure that it is working, I'll close #425
