### ISSUE TITLE
[Bug] Linux build fails

### ISSUE THREAD

**Issue by farkasma** [Drewol/unnamed-sdvx-clone#482]
**Describe the bug**
Trying to build after the big boi pull request, throws an error and fails to build.

**To Reproduce**
1. Attempt to update USC through pamac's built in AUR support.
2. Fail.

**Desktop:**
 - OS: Manjaro 5.11.22-2 kernel
 - GPU: Intel UHD 620
 - CPU: Intel Core i5-8250U
 - Version: trying to update from cb259d0 (according to pamac)

**Additional context**

**Log file**
Build log: https://pastebin.com/7bCRB66x
(Some additional parts are in Hungarian, sorry about that.)

**Comment by Drewol** [comment]
Hi, I removed some unused code in 182f94ac09519a7ebe18cbeb6e4edcaf7dcd751a so it might work now.

**Comment by farkasma** [comment]
Tried again, same thing happens still.

**Comment by Drewol** [comment]
Ah, it seems I missed one part, the error should at least look different now if it still doesn't work. Updated again 0f2db261d35594980f5b6841648b60974f2f6687

**Comment by farkasma** [comment]
It's good now, thank you for the quick fix.
