### ISSUE TITLE
Whenever I start the game all my audio apart from the game audio doesn't work. (FIXED)

### ISSUE THREAD

**Issue by Lightning7667** [Drewol/unnamed-sdvx-clone#484]
If I open USC all my audio on all other apps stops working. I have no idea why. I've tried doing the updater, re-installing the game, and checking if my speakers do something weird, but it never does anything. When I try watching Youtube with USC open it just says " Audio renderer error. Please restart your computer " and I can't watch anything, but when I close USC and refresh the page it magically works. 
If anybody would like to contact me on discord so I can show you my name and tag is:
iro#5674

**Comment by Hinara** [comment]
Can you try to uncheck WASAPI exclusive mode under System in usc settings ?

**Comment by Drewol** [comment]
User changed title to (FIXED), assuming non-issue
