### ISSUE TITLE
[Feature] Support for hit stats for long notes and lazers in result table

### ISSUE THREAD

**Issue by FajsiEx** [Drewol/unnamed-sdvx-clone#497]
**Is your feature request related to a problem? Please describe.**
I would like to have hit stats (criticals, nears, errors counts) for each object type. With current support, you can only get critical/error count of **both** long notes and lazers.

**Describe the solution you'd like**
Either add them to `result.noteHitStats` with field `type` that determines if the hit was chip/long/lazer or add some separate fields in the `result` table

**Describe alternatives you've considered**
I've considered storing the hit stats for long/lazer objects in hidden skin setting during gameplay, but that feels janky... I have no other solutions when drawing just from the `results` table

**Additional context**
I would like this to be implemented since exceed gear already has these stats in the result screen

![unknown-5.png](https://user-images.githubusercontent.com/32551223/127238112-1f89b734-8d73-40a8-a5c0-e94b3570b3ac.png)

Thank you for your consideration :)

**Comment by itszn** [comment]
You should be able to use the lane field to figure out if it is a laser (6 and 7).

6591fa2 Adds a `hold` field which is 0 for chips and >0 for holds.

**Comment by itszn** [comment]
I realized that the `noteHitStats` don't have the lasers so disreguard last message.

Now I have added `result.laserHitStats` and `result.holdHitStats` which hold the hitstats for those other events too.

**Comment by FajsiEx** [comment]
thanks!
