### ISSUE TITLE
Wide range lasers are incorrectly positioned

### ISSUE THREAD

**Issue by ASleepyCat** [Drewol/unnamed-sdvx-clone#50]
As shown in [these screenshots](https://imgur.com/a/zCD2i), wide range lasers seem to be offset to the left a little when positioned at the extremities. The red laser should be directly positioned on top of the blue laser.

[This is the chart that was used to take the screenshots with](https://github.com/Drewol/unnamed-sdvx-clone/files/1751062/exh.txt). The screenshots were taken at around measures 64 and 65, in case you want to check it yourself. Be sure to change the extension to .ksh.

**Comment by Drewol** [comment]
Looking at that chart you linked it seems as the red laser is an extended range laser while the blue laser is normal range and because of the relatively low resolution of laser placement ksh has they will not be exactly on the same position.

**Comment by Hinara** [comment]
So is it a bug or just a normal behaviour ?

**Comment by Drewol** [comment]
Pretty sure it's expected behavior.
