### ISSUE TITLE
[Bug] Linux AppImage builds not working

### ISSUE THREAD

**Issue by atirut-w** [Drewol/unnamed-sdvx-clone#501]
**Describe the bug**
Both the builds(generated by GH Actions) from `master` and `development` crashes with shader-related errors.

**To Reproduce**
(Deemed irrelevant since all the generated builds have this problem)

**Expected behavior**
The game should run as normal

**Screenshots**
![Screenshot_20210813_192547](https://user-images.githubusercontent.com/25323231/129356742-7c67f47c-5b93-49f7-a02f-051afd437e87.png)

**Desktop (please complete the following information):**
 - OS: Linux, OpenSUSE Tumbleweed
 - GPU: (Deemed irrelevant)
 - CPU: (Deemed irrelevant)
 - Version: GH Actions build from 79f7b4b325d722297aeae1411015f6da1352e3f9 and 9a3ab82472f5e486d10b4fbe160734d5033906a9

**Additional context**

**Log file**
If applicable, attach the log file or paste a snippet of it.

**Comment by JerwuQu** [comment]
Hey! I had somehow missed this issue...

I just tried the most recent AppImage built from the `develop` branch and it worked for me. Is this still an issue for you?

**Comment by atirut-w** [comment]
Nope. The issue is gone now. Just for the sake of my curiosity, do you 
happen to know what commit fixed this/why the issue happened?

**Comment by JerwuQu** [comment]
Ah, great!

Nope, no idea :]

**Comment by atirut-w** [comment]
> Nope, no idea :]

Git bisect maybe? Waiting for USC to compile is a pain for me tho
