### ISSUE TITLE
Chart Audio Doubles

### ISSUE THREAD

**Issue by sjieh** [Drewol/unnamed-sdvx-clone#51]
If you mash the start button on the controller during the result screen and enter the chart again, the audio playing during the chart will doubled, due to the song select audio clipping into the chart.

**Comment by Drewol** [comment]
I changed some things in 64cd2a1cfc18ce954f70f187f001ad134244e09a can you try to reproduce the bug again with these changes?

**Comment by sjieh** [comment]
Looks like it works fine now.

**Comment by Drewol** [comment]
Alright, closing this issue.
