### ISSUE TITLE
2 "Rainbow Controller" drivers detected, but the first one has (0 buttons, 0 axes, 0 hats)

### ISSUE THREAD

**Issue by Termibear** [Drewol/unnamed-sdvx-clone#517]
**Describe the bug**
There are 2 Rainbow Controllers being detected by USC whenever I start up the game.
I try to select the 2nd one to use in USC but it always defaults to the first one, and I am unable to move/press any buttons in-game with it.

**To Reproduce**
1. Plug in the Virgoo Turbocharger
2. Set the mode to controller mode instead of mouse mode
3. Start USC

**Expected behavior**
It should only detect 1 Rainbow Controller, with (12 buttons, 2 axes, 0 hats).

**Screenshots**
![image](https://user-images.githubusercontent.com/1110274/136366407-9b5c2bfa-6a70-4bed-b5b6-79aeecded9f0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU: RTX 2060 Super
 - CPU: i7-7700k
 - Version: 0.5.0

**Additional context**
It used to work on an older version, but I cannot remember which.

**Log file**
[log_usc-game.exe.txt](https://github.com/Drewol/unnamed-sdvx-clone/files/7301743/log_usc-game.exe.txt)

**Comment by anahisa1** [comment]
5.0 seems to be the only version that TC will not function on.

**4.0 Log showing that `[0, 1](12 buttons, 2 axes, 0 hats)` isn't peculiar to 5.0**
`[12:01:45][Info] Listing 2 Joysticks:`
`[12:01:45][Info] [0] "Rainbow Controller" (0 buttons, 0 axes, 0 hats)`
`[12:01:45][Info] [1] "Rainbow Controller" (12 buttons, 2 axes, 0 hats)`

TC functions fine in 4.0 .

**Comment by Termibear** [comment]
Thank you, it's working now.
