### ISSUE TITLE
segfault on launch

### ISSUE THREAD

**Issue by Azmarok** [Drewol/unnamed-sdvx-clone#52]
I have successfully built commit 54440a22ace363a5930b121cb5738c56a2e854fd on MX Linux 17. My system is up to date and using cmake 3.9 from the Debian stretch-backports repository. When I attempt to launch unnamed-sdvx-clone, I get a segfault after `Starting task "Loading common GUI elements"`.

[here is my inxi](https://pastebin.com/HCjgvQPc)  
[game output](https://pastebin.com/2i6J5hYz)  
[cmake output](https://pastebin.com/Y0Ms5eCq)  
[make output](https://pastebin.com/GpaRWeJC)

I'm not sure if there is something wrong with my build environment or if it's the project itself, but I am not familiar enough with C++ to figure this out on my own, sorry.

**Comment by Azmarok** [comment]
I have also tried building with clang instead of gcc, which instead causes the build to fail on `make`.

[cmake log](https://pastebin.com/dEZ3xkM6)  
[make log](https://pastebin.com/G2vKRk8S)

**Comment by Drewol** [comment]
For some reason that I've yet to find the game only properly works on linux when you're running it using an nVidia GPU. I'm sorry about this but I hope I can find a solution soon.

**Comment by Azmarok** [comment]
Have you tried debugging with Valgrind yet? I've tried compiling USC with debug symbols and then ran it using Valgrind, which seems to reveal that the issue starts in `Texture.cpp`, although I might be misunderstanding Valgrinds output.

**Comment by Drewol** [comment]
I think I've located the issue, it seems like the original creator of this used deprecated functions in `Texture.cpp` and my guess is that only nvidia still have these deprecated functions implemented on linux.

**Comment by Drewol** [comment]
I may have been able to resolve the issue in 062804bbe8

**Comment by Azmarok** [comment]
I am able to launch the game and browse the menus now, but I need to wait for these charts to download before I can test the whole thing.

**Comment by Drewol** [comment]
Closing because it seems like the crash was fixed at least.
