### ISSUE TITLE
MMod modspeed change

### ISSUE THREAD

**Issue by sjieh** [Drewol/unnamed-sdvx-clone#53]
If you quit a chart during a slower part of a chart when the ModSpeed is lower, sometimes the speed stays that way going into the next chart, I haven't tried it on XMod or CMod but I assume that they wouldn't be affected by this.

Here's a video to showcase it: https://www.youtube.com/watch?v=Mb5Haq8rSAs

**Comment by Drewol** [comment]
The changes in made in fd9eae01bfde62ebe4b16023efb9d2e1dee19ef6 might have fixed this, now it should only change your saved modspeed when you've actually manually adjusted the speed.

**Comment by sjieh** [comment]
Alright cool, looks good now.
