### ISSUE TITLE
speed mod issues

### ISSUE THREAD

**Issue by YungSenzu** [Drewol/unnamed-sdvx-clone#55]
everytime i have tried to play the game my hispeed and modspeed both decrease down to under 1 for hispeed and 12 for modspeed ive tried c mod and xmod i have also went into the files and changed the settings from there all with default settings and a fresh install the gameplay will start fine then all notes will group up in a total speed of under 100

**Comment by Drewol** [comment]
What are your bindings/control setup?

**Comment by YungSenzu** [comment]
everything default and also tried sdkl cm qp

**Comment by Drewol** [comment]
I'm not able to recreate this, the only way i can think of that would cause this is if your start button is for some reason still being held down during gameplay and also the knob buttons that lowers the highspeed.

**Comment by Hinara** [comment]
Seems to be a dead issue
