### ISSUE TITLE
Links broken in build.linux

### ISSUE THREAD

**Issue by Shob1** [Drewol/unnamed-sdvx-clone#557]
in the build.linux file some of the neccesary links are broken, also what package manager was used to get some of the libraries?

**Comment by Drewol** [comment]
Ok thanks, I will check for replacement links.
The automatic build uses apt but you should be able to use whichever is the default for your system but package names might differ some with some being prefixed with `lib` and/or suffixed with `-dev` eg `libsdl2-dev`
