### ISSUE TITLE
Charts Will Open, But nothing will happen 

### ISSUE THREAD

**Issue by Nerohybrid** [Drewol/unnamed-sdvx-clone#567]
I Have built this in linux using the guide provided, and it seems to be working, but when you load a chart, it plays it like its a chart with no notes that doesn't end, despite it not being that, i have tried it with several different charts and all of them do the same thing. when I was building it I turned openssl off, so i'm wondering if that has anything to do with it. I could have also built something wrong, but i'm not quite sure what i did wrong.

**Expected behavior**
For the chart to play

**Screenshots**
![image](https://user-images.githubusercontent.com/80785252/156907833-29377c8f-0717-4907-bf12-6e6dc1f4022f.png)
![image](https://user-images.githubusercontent.com/80785252/156907872-2d2e8381-c457-40be-8cb3-3252146cfc64.png)

**Laptop**
 - OS: Linux (Fedora 35 workstation)
 - GPU: Mesa Intel® HD Graphics 520 (SKL GT2)
 - CPU: intel® Core™ i5-6200U CPU @ 2.30GHz × 4 
 - Version: 0.5.0

also for clarification, I know USC runs on this pc's hardware, as I had previously had windows installed on it, and have just recently changed over to linux.

**Comment by mathieuarthur** [comment]
I have the exact same issues !

**Comment by Hinara** [comment]
Please try to download files from drewol website: https://www.drewol.me/Downloads/
0.5.0 is now a year old, bugs in it might have already been fixed

**Comment by Nerohybrid** [comment]
I don't know why i cant see this comment anymore, but this worked perfectly, thanks so much!
![image](https://user-images.githubusercontent.com/80785252/178026290-7efc670e-d8d2-4dfb-a9ce-3631ff90977a.png)
