### ISSUE TITLE
Offset Setting / Calibration

### ISSUE THREAD

**Issue by marcus13345** [Drewol/unnamed-sdvx-clone#57]
Recently, I successfully built this project on windows 10, 16299. But i noticed that I have a hard time getting similar scores as I did in Kshoot, so I did a side by side comparison of kshoot versus unnamed sdvx clone, with music synced.

Video [here](https://www.youtube.com/watch?v=wxiNJTjWW0E)

and it is clear the map is too far ahead of the music. An offset would be super useful to account for this.

Additionally, I'd love to help out with this project as much as i can in my free time. is there a slack, discord, gitter, etc for this project?

**Comment by nashiora** [comment]
https://discord.gg/GAGNwB

The configuration file has global and input offsets, they'll be added to the settings screen soon.

**Comment by Drewol** [comment]
Added offset settings to settings screen in ebee0914a160dbcbe02b53568317e4518c729716
