### ISSUE TITLE
Creating a release on Flathub

### ISSUE THREAD

**Issue by dawkurp** [Drewol/unnamed-sdvx-clone#575]
Preparing a Linux release on Flathub would involve developing a Flatpak build file and a flatpakref file.
Doing this would let more Linux users play the game as the install process for Flatpaks is even easier than the package manager for people coming over from Windows.
Most notably, playing on a Steam Deck would become possible as standard ways of installing Linux software are locked out by default and even once unlocked you run the risk of having your local build deleted by a system update.

Flatpak documentation mentions how to create a build file (example: [Flatpak first build documentation](https://docs.flatpak.org/en/latest/first-build.html))

Should this be too much of a hassle to prepare I can try at a later date to prepare a Flatpak build myself and see how complicated the process is.

**Comment by WingofaGriffin** [comment]
Would love to see this myself as well. I don't imagine it would be that hard, and happy to help if needed.
