### ISSUE TITLE
Local scores not being saved

### ISSUE THREAD

**Issue by ogami1972** [Drewol/unnamed-sdvx-clone#591]
**Describe the bug**
Profile's (player's) local scores are erased when switching between profiles

**To Reproduce**
1. Create two profiles, "A" and "B". Load profile "A".
2. Complete any chart for the first time. The score will be displayed as high score for that chart.
3. Back-out to settings and change profile to "B". Return to the previously played chart. "A"'s score will be gone, which I think is expected behavior. Play the chart as "B", and now you will see a score for "B".
4. Back-out to settings and change to profile "A". Return to chart, and there will once again be no score for "A", as if the chart had never been played.

**Expected behavior**
While I don't think scores from multiple profiles can be displayed, the profiles should have their own individual score history, yes?

**Screenshots**

https://youtu.be/pQ2kK2s0AdQ

**Desktop (please complete the following information):**
 - OS: Batocera (arch linux/wine)
 - GPU: RX550
 - CPU: i-5 4440
 - Version:2022-06-05_3fc60699

**Additional context**

**Log file**

**Comment by ogami1972** [comment]
Hello!

Reopening with video.

https://youtu.be/pQ2kK2s0AdQ

**Comment by Drewol** [comment]
Hi, if you send your maps.db file I can take a look at how your scores have been saved.

**Comment by ogami1972** [comment]
Hello!



Here's the file. Thank you!

[ogami1972_maps_db.zip](https://github.com/Drewol/unnamed-sdvx-clone/files/8855413/ogami1972_maps_db.zip)

**Comment by Drewol** [comment]
For the song specifically showcased in the video you appear to have a duplicate of it, at the moment scores only show for one entry if there are duplicates.

the duplicate charts are located at:
`songs\TAYEUS\Taes Fun Pack\nidhogg` and
`songs\B4UTmay2018\01_ishoku\04_Nidhogg`

**Comment by ogami1972** [comment]
cool, thank you so much, i knew there was dupe, assumed they would just be treated as different charts as they are different paths. I'll try removing that and see if the behavior changes. Or maybe try another chart i know i only have one of.

**Comment by ogami1972** [comment]
ok, so here's what I found:

1. Removing the duplicate did indeed cause the scores to appear. There is a related issue in solving this. deleting a single duplicate within the game causes both copies to be deleted. Duplicates must be deleted through external file manager?
2. The scores remain the same when profiles are changed, but the name changes on the scores. I've included a couple of pics. 

![IMG_20220607_132045_625](https://user-images.githubusercontent.com/105079419/172456175-e0f0d5f0-25c2-4f8c-9ce5-282adef35ba1.jpg)
![IMG_20220607_132137_377](https://user-images.githubusercontent.com/105079419/172456204-178c1895-22d6-46fc-b819-73531f51f705.jpg)

Thanks again for looking at this with me, i find it very very interesting.

**Comment by ogami1972** [comment]
ok, yeah, the library is a mess of dupes, but you can file that under "not my problem", lol. I'll clean it up, maybe release my own library ;)

As for the scores, I can see that it is, in reality, expected behavior. I will put in a feature request for scores to be somehow tied to profiles. Ideally, I'd like to see the skill analyzer section work for each player/profile, i.e. you can test your skill there and see your personal progression. But that's another thing.

closed and thank you.
