### ISSUE TITLE
[Bug] Nautica not downloading any charts that contain Japanese+Certain Unicode characters.

### ISSUE THREAD

**Issue by Loopsyded** [Drewol/unnamed-sdvx-clone#613]
**Describe the bug**
When downloading any song through the in-game browser that contains Japanese characters, the status will be stuck on "Downloading" and no files except the song preview will download.

**To Reproduce**
1. Go to nautica
2. Download any song with Japanese characters

**Expected behavior**
Charts which contain only English characters will download within a couple of seconds.

**Screenshots**
![image](https://user-images.githubusercontent.com/11378185/181468998-97f6f963-d340-4061-9141-609ad39e6b53.png)

**Desktop (please complete the following information):**
 - OS: [Arch Linux]
 - GPU: 8 RDNA 2 CUs, 1.0-1.6GHz
 - CPU: Zen 2 4c/8t, 2.4-3.5GHz
 - Version: 0.5.0 2022-07-26_e8ede61c

**Comment by Hinara** [comment]
Have you your log file 
I can't reproduce on the last commit under Fedora 36
Version: 0.5.0
Git commit: 2022-07-27_5253994f

**Comment by Loopsyded** [comment]
> Have you your log file I can't reproduce on the last commit under Fedora 36 Version: 0.5.0 Git commit: 2022-07-27_5253994f


[log_usc-game.exe.txt](https://github.com/Drewol/unnamed-sdvx-clone/files/9215499/log_usc-game.exe.txt)

Here it is, although if you haven't been able to reproduce it on Fedora 36, it's most likely something on my side. I'll try to see what's wrong on my machine.

**Comment by Loopsyded** [comment]
Reading the log again I'm not sure how I missed it but it doesn't seem like it's pointing to the right directory. I think it's probably better to build it instead so I'll see if the issue still persists after that.

**Comment by Loopsyded** [comment]
After rereading the log, what stands out is 
> [21:29:51][Warning] Can't run ScanFiles, "D:\Game\profiles/" is not a folder
[21:29:51][Warning] No sample named "result" found.

but even then it's weird that only songs which contain Japanese characters can't download. There's no issues with the other English charts.

**Comment by Loopsyded** [comment]
I just updated to the latest development version and the issue has fixed itself.

**Comment by Loopsyded** [comment]
It seems that songs that contain certain unicode characters break as well, for example the "×" symbol from these songs.
https://ksm.dev/songs/9a2a4040-0710-11ed-b69a-9d985830125d
https://ksm.dev/songs/eee7b860-0b7b-11ed-91d9-d52e4f9ad77a

**Comment by Loopsyded** [comment]
Upon digging some more, I'm now even more confused. 
While the majority of songs that contain special characters such as:
https://ksm.dev/songs/9a2a4040-0710-11ed-b69a-9d985830125d
https://ksm.dev/songs/eee7b860-0b7b-11ed-91d9-d52e4f9ad77a
As well as songs which contain Greek symbols, Kanji, and Katakana do not download properly,

I have found songs which do download despite the fact that they contain Japanese characters. For example, these songs all contain either Kanji or Hiragana, but pose no issues: 
https://ksm.dev/songs/f5d8e4c0-dcd6-11ec-9e41-bdf5c10d7a0f
https://ksm.dev/songs/7b3524e0-e0e6-11ec-bf30-e5b37566c440
https://ksm.dev/songs/e16e0870-05e9-11ed-9c8d-8d4995fcfa81
https://ksm.dev/songs/db6c68a0-fc7a-11ec-a700-df7fa7bff59e
https://ksm.dev/songs/27e65170-f589-11ec-a3aa-b5de2704283a
https://ksm.dev/songs/e5640100-f2da-11ec-be2c-bb5329bb84ca

I still suspect that it has to do with the language used in song titles/descriptions since I haven't been able to find a song written entirely in English that refused to download yet but I'm not sure what exactly could be going wrong.

[log_usc-game.exe.txt](https://github.com/Drewol/unnamed-sdvx-clone/files/9219461/log_usc-game.exe.txt)

**Comment by Hinara** [comment]
Wait are you under windows or linux, if you are under linux, is your USC installation on a FAT32 or some kind of partition which might cause trouble with file encoding ?

**Comment by Loopsyded** [comment]
I'm using linux with ext4. I didn't even think of it but I think that's probably what's causing the issue. I'll try it again on a different kind of partition and see how it goes.

**Comment by Hinara** [comment]
I'm also on ext4 and this doesn't cause any trouble, so I really does the problem comes from :/

**Comment by Loopsyded** [comment]
Haha that definitely saves me time on reformatting my drive. I'm going to try rebuilding and see if something will fix itself, or try running it with proton/wine as well.

**Comment by Hinara** [comment]
You can also try the app image:
https://www.drewol.me/Downloads/Game_linux_AppImage.zip

**Comment by Loopsyded** [comment]
YOU ARE A LIFE SAVER.
I can't believe I didn't see that when I was looking through drewol.me/downloads
There's no issues at all anymore. I really can't thank you enough.

**Comment by Loopsyded** [comment]
Sorry to post here again, but I tried running the game through a Lutris install script and the Nautica downloading works completely fine on the 0.4.0 build of USC, but it breaks as soon as you update to 0.5.0. 

Would it be possible to update the game, then rollback only the scripts related to nautica downloading?
