### ISSUE TITLE
Window does not have a class or name - makes linking a .desktop entry with it impossible

### ISSUE THREAD

**Issue by nermolov** [Drewol/unnamed-sdvx-clone#62]
The window currently has no class or name other than "Main"

The output of `xprop WM_CLASS` is `WM_CLASS(STRING) = "Main", "Main"`

This removes the potential to use the StartupWMClass field in a .desktop file to tie a launched application with an entry.

**Comment by Drewol** [comment]
I dont know but fb9de1108a7d46e642b67dbd1614be8433e67f96 might have fixed this. You'll have to run `cmake .` again before building

**Comment by Hinara** [comment]
Can be close
