### ISSUE TITLE
cmake command

### ISSUE THREAD

**Issue by itsnotjoke** [Drewol/unnamed-sdvx-clone#651]
This is the first time I've tried to install this kind of stuff but when I run the cmake command I get this error,

 CMake Error at /usr/local/Cellar/cmake/3.27.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.27.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.27.5/share/cmake/Modules/FindJPEG.cmake:106 (find_package_handle_standard_args)
  CMakeLists.txt:53 (find_package)

Any help would be extremely appreciated

**Comment by Hinara** [comment]
Just for reference (as it's already close) you need to install all dependencies which are written here
https://github.com/Drewol/unnamed-sdvx-clone/blob/develop/build.linux
