### ISSUE TITLE
Mac M1 - Make  Error[Bug]

### ISSUE THREAD

**Issue by Plopy** [Drewol/unnamed-sdvx-clone#654]
Hi !

When I tried to install, i follow these steps : 
brew install cmake freetype libvorbis sdl2 libpng jpeg libarchive libiconv
git clone https://github.com/Drewol/unnamed-sdvx-clone.git
cd unnamed-sdvx-clone
git submodule update --init --recursive
./mac-cmake.sh

No problem

But when I tried to make : 
[ 85%] Building CXX object Main/CMakeFiles/usc-game.dir/src/ScoreScreen.cpp.o

In file included from /Users/danynguyendinhthinh/Desktop/unnamed-sdvx-clone/Main/src/ScoreScreen.cpp:1:
In file included from /Users/danynguyendinhthinh/Desktop/unnamed-sdvx-clone/Main/./stdafx.h:82:
In file included from /Users/danynguyendinhthinh/Desktop/unnamed-sdvx-clone/Main/include/nuklear/nuklear_sdl_gl3.h:17:
/opt/homebrew/include/SDL2/SDL_opengl.h:108:11: warning: 'GLAPI' macro redefined [-Wmacro-redefined]
#  define GLAPI __attribute__((visibility("default")))
          ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers/gl3.h:106:9: note: previous definition is here
#define GLAPI extern
        ^
In file included from /Users/danynguyendinhthinh/Desktop/unnamed-sdvx-clone/Main/src/ScoreScreen.cpp:17:
/Users/danynguyendinhthinh/Desktop/unnamed-sdvx-clone/Main/include/ChatOverlay.hpp:26:7: warning: 'OnKeyPressedConsume' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        bool OnKeyPressedConsume(SDL_Scancode key);
             ^
/Users/danynguyendinhthinh/Desktop/unnamed-sdvx-clone/Main/include/GuiUtils.hpp:19:15: note: overridden virtual function is here
        virtual bool OnKeyPressedConsume(SDL_Scancode code) { return m_isOpen; };
                     ^
In file included from /Users/danynguyendinhthinh/Desktop/unnamed-sdvx-clone/Main/src/ScoreScreen.cpp:18:
/Users/danynguyendinhthinh/Desktop/unnamed-sdvx-clone/Main/include/Gauge.hpp:79:7: warning: 'GetClearState' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        bool GetClearState() const;
             ^
/Users/danynguyendinhthinh/Desktop/unnamed-sdvx-clone/Main/include/Gauge.hpp:57:7: note: overridden virtual function is here
        bool GetClearState() const;
             ^
/Users/danynguyendinhthinh/Desktop/unnamed-sdvx-clone/Main/include/Gauge.hpp:80:14: warning: 'GetName' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        const char* GetName() const;
                    ^
/Users/danynguyendinhthinh/Desktop/unnamed-sdvx-clone/Main/include/Gauge.hpp:58:14: note: overridden virtual function is here
        const char* GetName() const;
                    ^
/Users/danynguyendinhthinh/Desktop/unnamed-sdvx-clone/Main/include/Gauge.hpp:81:7: warning: 'FailOut' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        bool FailOut() const;
             ^
/Users/danynguyendinhthinh/Desktop/unnamed-sdvx-clone/Main/include/Gauge.hpp:34:15: note: overridden virtual function is here
        virtual bool FailOut() const {
                     ^
/Users/danynguyendinhthinh/Desktop/unnamed-sdvx-clone/Main/include/Gauge.hpp:82:12: warning: 'GetType' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        GaugeType GetType() const;
                  ^
/Users/danynguyendinhthinh/Desktop/unnamed-sdvx-clone/Main/include/Gauge.hpp:59:12: note: overridden virtual function is here
        GaugeType GetType() const;
                  ^
/Users/danynguyendinhthinh/Desktop/unnamed-sdvx-clone/Main/include/Gauge.hpp:115:14: warning: 'GetName' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        const char* GetName() const;
                    ^
/Users/danynguyendinhthinh/Desktop/unnamed-sdvx-clone/Main/include/Gauge.hpp:80:14: note: overridden virtual function is here
        const char* GetName() const;
                    ^
/Users/danynguyendinhthinh/Desktop/unnamed-sdvx-clone/Main/include/Gauge.hpp:116:12: warning: 'GetType' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        GaugeType GetType() const;
                  ^
/Users/danynguyendinhthinh/Desktop/unnamed-sdvx-clone/Main/include/Gauge.hpp:82:12: note: overridden virtual function is here
        GaugeType GetType() const;
                  ^
/Users/danynguyendinhthinh/Desktop/unnamed-sdvx-clone/Main/src/ScoreScreen.cpp:562:2: error: constructor for 'ScoreScreen_Impl' must explicitly initialize the member 'm_irResponse' which does not have a default constructor
        ScoreScreen_Impl(class Game* game, MultiplayerScreen* multiplayer,
        ^
/Users/danynguyendinhthinh/Desktop/unnamed-sdvx-clone/Main/src/ScoreScreen.cpp:53:21: note: member is declared here
        cpr::AsyncResponse m_irResponse;
                           ^
/opt/homebrew/include/cpr/async_wrapper.h:20:7: note: 'cpr::AsyncWrapper<cpr::Response, false>' declared here
class AsyncWrapper {
      ^
8 warnings and 1 error generated.
make[2]: *** [Main/CMakeFiles/usc-game.dir/src/ScoreScreen.cpp.o] Error 1
make[1]: *** [Main/CMakeFiles/usc-game.dir/all] Error 2

If you have any solution !

Thanks a lot :)

**Comment by AlexaL-P** [comment]
I get a different error when running `./mac-cmake.sh` on my M1 Mac Mini; as follows:

``-- The C compiler identification is AppleClang 15.0.0.15000040
-- The CXX compiler identification is AppleClang 15.0.0.15000040
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Freetype: /opt/homebrew/lib/libfreetype.dylib (found version "2.13.2") 
-- Found ZLIB: /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/lib/libz.tbd (found version "1.2.12")  
-- Found SDL2: /opt/homebrew/include  
-- Found PNG: /opt/homebrew/lib/libpng.dylib (found version "1.6.40") 
CMake Error at /opt/homebrew/Cellar/cmake/3.27.8/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.27.8/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.27.8/share/cmake/Modules/FindJPEG.cmake:106 (find_package_handle_standard_args)
  CMakeLists.txt:53 (find_package)


-- Configuring incomplete, errors occurred!``

can't tell if the error is related but I imagine it's useful to have the info in one place

**Comment by Asapmoy87** [comment]
> I get a different error when running `./mac-cmake.sh` on my M1 Mac Mini; as follows:
> 
> ```
> -- The C compiler identification is AppleClang 15.0.0.15000040
> -- The CXX compiler identification is AppleClang 15.0.0.15000040
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found Freetype: /opt/homebrew/lib/libfreetype.dylib (found version "2.13.2") 
> -- Found ZLIB: /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/lib/libz.tbd (found version "1.2.12")  
> -- Found SDL2: /opt/homebrew/include  
> -- Found PNG: /opt/homebrew/lib/libpng.dylib (found version "1.6.40") 
> CMake Error at /opt/homebrew/Cellar/cmake/3.27.8/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
> Call Stack (most recent call first):
>   /opt/homebrew/Cellar/cmake/3.27.8/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
>   /opt/homebrew/Cellar/cmake/3.27.8/share/cmake/Modules/FindJPEG.cmake:106 (find_package_handle_standard_args)
>   CMakeLists.txt:53 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> ```
> 
> can't tell if the error is related but I imagine it's useful to have the info in one place



I got this error on my mac as well

**Comment by Asapmoy87** [comment]
I got this after after running ./mac-cmake.sh


CMake Error at /opt/homebrew/Cellar/cmake/3.27.8/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
> Call Stack (most recent call first):
>   /opt/homebrew/Cellar/cmake/3.27.8/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
>   /opt/homebrew/Cellar/cmake/3.27.8/share/cmake/Modules/FindJPEG.cmake:106 (find_package_handle_standard_args)
>   CMakeLists.txt:53 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!

**Comment by Hinara** [comment]
Did you follow the instructions and executed `brew install cmake freetype libvorbis sdl2 libpng jpeg libarchive libiconv` before ?
https://github.com/Drewol/unnamed-sdvx-clone#macos

**Comment by Asapmoy87** [comment]
> Did you follow the instructions and executed `brew install cmake freetype libvorbis sdl2 libpng jpeg libarchive libiconv` before ? https://github.com/Drewol/unnamed-sdvx-clone#macos

I have I've even tried to reinstall multiple times. Just keep getting the same error all the other dependecies seem to work.

**Comment by Hinara** [comment]
Maybe linked to install path error :/ #471

**Comment by SkyLeite** [comment]
@Asapmoy87 I posted a fix for that issue in #471
