### ISSUE TITLE
[Feature] Submit to Flathub

### ISSUE THREAD

**Issue by 0chroma** [Drewol/unnamed-sdvx-clone#664]
Hello!

I've finally gotten a flatpak build ready for flathub submission! If you'd like I can submit it on your behalf, but I figured I'd reach out first in case you wanted to submit it yourself.

I can also make an icon quickly for you if you'd like.

You can find the process here: https://docs.flathub.org/docs/for-app-authors/submission/#how-to-submit-an-app

If you'd like to submit it yourself, you're free to clone my repo and use it to submit: https://github.com/0chroma/usc-flatpak

Let me know how you'd like to proceed. Thanks!

**Comment by Drewol** [comment]
Hi, 

There was someone working on an icon so I'll check how that's coming along. It sounds like it doesn't make a big difference who submits it so you can go ahead with that.

**Comment by 0chroma** [comment]
sounds good! I'm on it ^^

**Comment by Drewol** [comment]
Looks like there are some issues with the dependencies. For the curl issue there is a option to build with `USE_SYSTEM_CPR` which might help, added for another packaging reason #657.

**Comment by 0chroma** [comment]
oh actually updating cpr would be perfect, since then I can use the runtime version of curl included. I saw there was an option for `USE_SYSTEM_CURL` as well so that'll solve that issue!
