### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Jason25841** [Drewol/unnamed-sdvx-clone#666]
Last week I just followed README and compiled USC, it ran successfully.
But I deleted what I have compiled and cloned USC with Git again, and the error occurred. I retried many times but nothing happened.

![20240324_14h31m50s_grim](https://github.com/Drewol/unnamed-sdvx-clone/assets/109329792/8bfaacdd-81ce-4178-aa32-7939da410daf)

 - Device: RPi 4B 2GB ver.
 - OS: Recent RPi OS
 - GPU: Broadcom VideoCore VI
 -  CPU: Broadcom BCM2711
 - Version: Recent commit

This is my first issue in GitHub and I created this issue with template in GitHub Mobile by accident just now. I want to say sorry to the owner and all of you.
Thanks.

**Comment by Hinara** [comment]
I think you might have forgotten the `git submodule update --init --recursive`
Which means the third_party folder might not have ben correctly populated

**Comment by Jason25841** [comment]
Before the problem happened, I have done it, but it had a pause at half. And I have compiled successfully on my amd64 machine with ethernet just now.
I think the reason is that my Wi-Fi connection is bad at where I put my RPi, or I'm in China Mainland, and break off my connection to GitHub at half while I was installing submodules.
I'll retry later, thanks.

**Comment by Jason25841** [comment]
yep, It's weekend now and I just compiled successfully on my raspberry pi just now, by copy the source code through USB drive, finding OpenGL problem but i think It's not a big deal

I'll buy an ethernet cable and clone this project with git again, Nothing needs to help, and i think i will success next time

- Thanks :D
