### ISSUE TITLE
Question, Flatpak, Where does the game stores installed songs and skins?

### ISSUE THREAD

**Issue by Akeem29** [Drewol/unnamed-sdvx-clone#688]
The flatpak release (https://flathub.org/apps/me.drewol.Unnamed-SDVX-Clone) is marked as unverified, so I'm not sure whether I should write this question here or in another place. If I need to re-ask somewhere else - please let me know.
My problem is - I can't find the folder where the flatpak version stores the installed songs and where the skins should be installed. The command flatpak info --show-location me.drewol.Unnamed-SDVX-Clone shows the place in which game's executable and libraries are stored, as well as the default skin, but placing third-party skins alongside the default skin does nothing and also - songs that were installed through in-game menu are nowhere to be found, despite them existing somewhere in the system considering that the game plays the songs without issues

**Comment by Drewol** [comment]
Writing here is fine.

I'm not 100% sure if flatpak always places it here but on my system the song and skin can be placed in:
`~/.var/app/me.drewol.Unnamed-SDVX-Clone/data/unnamed-sdvx-clone`

**Comment by Akeem29** [comment]
Thank you! The flatpak version uses this very directory
