### ISSUE TITLE
License

### ISSUE THREAD

**Issue by notpushkin** [Drewol/unnamed-sdvx-clone#77]
Hey, thanks for such an awesome project! It's nice to see more and more open source rhythm games out there. :)

I've noticed that the repository lacks a license – is there some concrete reason you omitted it or it was just accidentally?

**Comment by Drewol** [comment]
As you can see this repo is a fork of a project that is not being actively developed anymore and that repo does not have a license and I'm simply not comfortable adding a license to this repo without asking for permission from the original creator.

**Comment by notpushkin** [comment]
Makes sense! (I wanted to mention both you and @guusw on this issue but totally forgot before sending).

@guusw, thank you too for your amazing work on USC! Would you mind adding a license to your project?

**Comment by guusw** [comment]
Hey, I added the MIT license to the original repository. Let me know if it causes any issues or you have a better suggestion.

**Comment by Drewol** [comment]
I've added a license now that I think looks correct but if you have any issues with it I can make changes @guusw 

closing this issue for now
