### ISSUE TITLE
Camera Bug on DropZ-Line-

### ISSUE THREAD

**Issue by fdigl** [Drewol/unnamed-sdvx-clone#81]
Bug seen on EXH/16, the track notes seem a little erratic during BPM changes, most notably when the speed picks up from the mid-song slowdown. Same chart works fine in latest KSM.

**Comment by fdigl** [comment]
Yes, 800-900 C-Mod. Do you need footage of it occuring?

**Comment by Drewol** [comment]
nah, C-Mod has been broken like that for a very long time. Just try to play with M-Mod at the moment and I'll see if I can fix C-Mod in the near future.

**Comment by fdigl** [comment]
Got it, you've been doing an awesome job so far! Thanks for keeping this going!

**Comment by Drewol** [comment]
Anyway... It should be fixed now, I haven't done any extensive testing but it seems to work now after dd3350bc366d4ea0e3b843f691111d8894daf424
