### ISSUE TITLE
Game crashes when it's trying to load a deleted song

### ISSUE THREAD

**Issue by ultrakiller2** [Drewol/unnamed-sdvx-clone#88]
~~It's will be good if the game'd just give an error message and go back to main menu.~~
I think, automatic song deletion from database if the file can't be found (but not it's results) and manual song database remake would be optimal solution
Also, the tittle is to be changed, but I can't find right words
![clipboarder 2018 11 06-002](https://user-images.githubusercontent.com/25438100/48055938-cc75a580-e1c1-11e8-94a7-5974018a55b8.png)
[log_Main_Release.exe.txt](https://github.com/Drewol/unnamed-sdvx-clone/files/2552531/log_Main_Release.exe.txt)

**Comment by YChvanov** [comment]
Wrong. Game crashes when it's trying to load deleted song.
[log_Main_Release.exe.txt](https://github.com/Drewol/unnamed-sdvx-clone/files/2552531/log_Main_Release.exe.txt)

**Comment by Hinara** [comment]
I find out why
So m_SearchThread is launched twice in a short period of time before Update has been called
I think we need to prevent m_SearchThread to launch if m_pendingChanges.size() is different from 0

**Comment by Hinara** [comment]
BTW is that normal that SongSelect::Init and SongSelect::Restore are both called ?

**Comment by Drewol** [comment]
init and restore both being called when a screen is created and instantly showed is expected behavior. But if there is duplicate logic in them then it needs to be considered where it makes the most sense to call that logic if calling it twice causes issues.
