### ISSUE TITLE
Text glitched on Settings button

### ISSUE THREAD

**Issue by ghost** [Drewol/unnamed-sdvx-clone#9]
OS: Windows 10 Pro 64-bit, Version 1703, Build 15063.674
Commit: [d777a48](https://github.com/Drewol/unnamed-sdvx-clone/commit/d777a4858efe79b9bfa5a5ea97b314770646b381)

![](https://imgur.com/Ks0enzy.png)

**Comment by Drewol** [comment]
I changed a small thing in text rendering in 85078127c82cc9e21c10f501ab57fcc9a43f5091 but I don't think it was the issue shown in this image but if you can try and see if it's still there.
