### ISSUE TITLE
[UI & Feature Suggestions] Several quality of life improvements

### ISSUE THREAD

**Issue by fdigl** [Drewol/unnamed-sdvx-clone#91]
Common:
- Ability to change font properties used to display FPS
- Notification of updates available

Title Screen:
- Ability to add BGM
- Ability to add selection and back button SFX
- Ability to control using controller/keyboard

Song wheel:
- Ability to use scroll wheel to scroll through songs
- Ability to sort by artist
- Ability to skip to next letter/section (similar to clone hero)
- Ability to create courses in-game
- Ability to set laser colors in the mod menu
- Ability to disable FX and laser SFX in mod menu
- Ability to add favorites (similar to KSM)
- Ability to show song jackets on the song wheel (visual aid when selecting song)
- Ability to view highscores with FX-R like in previous versions
- Ability to add BGM music, selection SFX

Gameplay:
- New section of UI that slides in from left with lua (where player name and card would show in SDVX)
- Ability to change slide-in speed of UI elements when a song is loaded (kind of possible but janky)
- Ability to view previous scores and compare current score to them (similar to osu!)
- Ability to view effector name in song info panel using lua skinning
- Ability to enable gauge percentage via lua skinning
- Ability to add SFX to outro (track finish, fail, FC, perfect, and excessive rate crash)
- Ability to use ARS (if hard gauge fails, switch to normal)
- Ability to play courses
- Ability to play charts at different speeds (like clone hero)
- Ability to quickly exit a song (bypass outro text) by double tapping the exit button
- Ability to disable the functions of F5, F8, TAB, etc keys
- Ablitiy to create gauge animations like in KSM
- Ability to toggle song distortion on track end
- Ability to toggle ending gameplay on chart end and on song end
- Ability to use different backgrounds on a per-song basis (including custom ones provided in the song folder)
- Ability to adjust the size of the playing field (I find myself wanting it smaller on a 4k large monitor)
- Hide cursor automatically (I always find myself having to move the mouse for it to disappear)
- Change background state if passing or failing
- Controller overlay similar to the one I use with NohBoard here: https://www.youtube.com/watch?v=JEo6oFDzlEg

Results:
- Ability to use the old performance graph (red for failing, green for passing)
- Ability to quickly replay a song using the F5 key
- Ability to hide high scores
- Ability to add BG music, different depending on clear state
- Cut off applause and BG audio when exiting the results screen quickly
- Record replays similar to osu!mania, playback by clicking highscore in song wheel (see suggestions)
- Screenshot button (maybe integrate with ShareX)

General:
- Practice mode that allows you to practice specific sections of charts and speeds
- Calibration mode that allows for testing latency calibration in-game
- Multiple profiles to keep scores and settings separate, but can compare scores with other profiles
-- Ability to get profile name and associated image with lua for use with the first suggestion for Gameplay
- Ability to disable particles and glowing shaders in the options menu
- Ability to disable background in the options menu
- Ability to rebind ESC, F5, PGUP/PGDN, etc
- Ability to exit options menu with back button

These are just suggestions, the game as-is is looking great so far. Hopefully some of these are interesting enough to make it in! Of course, I'm also learning how this was all made and I might be able to contribute someday in the future.

I was wondering how to access the open in editor feature. I was also wondering if it's possible to add text fill alpha and making animations such as transforming position through lua. You've been doing an awesome job with the updates!

**Comment by Drewol** [comment]
I would really prefer it if you could split this issue into multiple smaller issues with maybe just a couple (related) suggestions per issue as this list is pretty long and I would like to be able to close the issues as the features get made or dismissed

**Comment by fdigl** [comment]
Alrighty, I'll split it into smaller groups
