### ISSUE TITLE
[Feature] Practice mode

### ISSUE THREAD

**Issue by fdigl** [Drewol/unnamed-sdvx-clone#99]
This would be a mode that allows you to practice specific sections of charts and speeds, similar to Clone Hero but the player can choose specifically where they would want to practice instead of spamming PGUP to get to the part they want to practice.

**Comment by 123jimin** [comment]
I've been making a practice mode ([the branch](https://github.com/123jimin/unnamed-sdvx-clone/tree/practice-mode)), and so far I have implemented the basic gameflow.

Here's how it is planned to work:
- From the song selection scene, a user can enter the _practice setup mode_.
  - Practice setup mode is a game scene where the chart is autoplayed.
  - A user can pause, play, or navigate the chart.
  - A user can set various practice mode options.
    - Toggle looping: whether to restart on fail / on success
    - Playback speed
    - Fail conditions: one of the following
      - Max possible score less than ___
      - Max possible grade less than ___ (actually an alias of above option)
      - Miss count more than ___
      - Miss + near count more than ___
- From the _practice setup_ mode, a user can enter the _practice mode_.

So far all _functionalities_ are implemented, and the very basic way of using them is implemented (except toggling looping (always enabled) and setting fail conditions).
The UIs for following tasks need to be devised before it's usable:

1. How to enter the practice setup mode from song selection screen?
  - I would like to address this together with autoplay mode, which is currently nearly impossible to discover.
2. How to navigate / set various options in the practice mode?
  - I think that something similar to `gamesettingsdialog.lua` can be used here.
3. How to provide various practice mode-related informations?
  - Examples: current playback speed, current fail condition status, ...
